### ISSUE TITLE
the x parameter in the function renderValue is always undefined

### ISSUE THREAD

**Issue by fjossinet** [ramnathv/htmlwidgets#100]
Dear all,

I'm using the current version of shiny and htmlwidgets, with R 3.1.3 and RStudio 0.99.386 under OSX. Do you see any reason why my x parameter is always undefined in my own widget. In the following example x$svg is the content of an SVG file. Thanks for your help!!

file cola.R

```R
cola <- function(fileName, width = NULL, height = NULL) {

  # forward options using x
  x<- list()
  x$svg <- paste(readLines(fileName), collapse="")
  
  # create widget
  htmlwidgets::createWidget(name = 'cola', x, width = width, height = height, package = 'cola')
}
```

file cola.js

```javascript
HTMLWidgets.widget({

  name: 'cola',

  type: 'output',

  initialize: function(el, width, height) {
    
  //create a vis object with the library d3.js  
    return {
      vis : vis
    }

  },

  renderValue: function(el, x, instance) {
    console.log(el); //OK!
    console.log(x); //always undefined according to the javascript console
    console.log(instance); //OK!
  },

  resize: function(el, width, height, instance) {

  }

});
```

file server.R
```R
output$test <- renderCola({
    cola(system.file("htmlwidgets/examples/sucrose.svg", package = "cola"))
  })
```

**Comment by timelyportfolio** [comment]
Replying from my phone and will fill out more in a bit but I think you just need to change x=x

  htmlwidgets::createWidget(name = 'cola', x=x, width = width, height = height, package = 'cola')

**Comment by fjossinet** [comment]
Thank you for your quick answer. Unfortunately this doesn't fix the problem. I have uploaded my widget to github https://github.com/fjossinet/cola. Thanx!

**Comment by timelyportfolio** [comment]
It will probably be easiest to debug without shiny first.  Does `cola` without `shiny` work correctly?  I'm installing now.

By the way, I love `webcola`, so am anxious to see what you have planned.

**Comment by fjossinet** [comment]
if i do something like:

```R
c<- cola(fileName=system.file("htmlwidgets/examples/sucrose.svg", package = "cola"))
c$x
````

This prints:
```R
$svg
[1] "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><!--Created with Dunnart (http://www.csse.monash.edu.au/~mwybrow/dunnart/)--><svg   xmlns:dunnart=\"http://www.csse.monash.edu.au/~mwybrow/dunnart.dtd\"   xmlns:dc=\"http://purl.org/dc/elements/1.1/\"   xmlns:cc=\"http://web.resource.org/cc/\"   xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"   xmlns:svg=\"http://www.w3.org/2000/svg\"   xmlns=\"http://www.w3.org/2000/svg\" [....]
```

So it seems that cola alone works. And by the way, webcola is great ;-)

**Comment by timelyportfolio** [comment]
Ok, it works on my end.  Do you have the newest `jsonlite`, `shiny`, and `htmlwidgets`?

```
devtools::install_github(c("jeroenooms/jsonlite","rstudio/shiny","ramnathv/htmlwidgets"))
```

**Comment by fjossinet** [comment]
I have updated my libs and now its fine!! Thanx a lot!! I will push my work forward now. I stay in touch with you to show you my final result. For now, i just want to be able to load webcola from within a Rmarkdown presentation. This is my first htmlwidget. Shiny + htmlwidgets could be my next favorite toys ;-) Thanx!!

**Comment by ramnathv** [comment]
Great. Looking forward to the cola widget.
