### ISSUE TITLE
saveWidget self contained encoding issue

### ISSUE THREAD

**Issue by jpmarindiaz** [ramnathv/htmlwidgets#105]
I am having an issue saving an htmlwidget (self contained).

```r
devtools::install_github("jpmarindiaz/d3plus")
library(d3plus)
countries <- read.csv(system.file("data/countries.csv", package = "d3plus"))
s <- d3plus("tree", countries)
htmlwidgets::saveWidget(s,"index.html")
```
Looking at the console, d3 cannot be loaded because there are some encoding issues:
Look at the special characters in the d3.js v3.5.5 file:
`var ε = 1e-6, ε2 = ε * ε, π = Math.PI, τ = 2 * π, τε = τ - ε, halfπ = π / 2, d3_radians = π / 180, d3_degrees = 180 / π;
`https://github.com/jpmarindiaz/d3plus/blob/master/inst/htmlwidgets/lib/d3-v3.5.5/d3.js#L1261

They get encoded into this (when the self contained = TRUE)
`var Îµ = 1e-6, Îµ2 = Îµ * Îµ, Ï€ = Math.PI, Ï„ = 2 * Ï€, Ï„Îµ = Ï„ - Îµ, halfÏ€ = Ï€ / 2, d3_radians = Ï€ / 180, d3_degrees = 180 / Ï€;`

Thanks for your help!

**Comment by ramnathv** [comment]
Use the minified version of `d3.js`. That will solve the issue.

**Comment by jpmarindiaz** [comment]
Awesome, it worked. Thanks so much!
