### ISSUE TITLE
rmarkdown with include FALSE

### ISSUE THREAD

**Issue by jpmarindiaz** [ramnathv/htmlwidgets#108]
Hi

Before I upgraded to rmarkdown package version 0.6.1. I could simply use include = FALSE in the R chunks and I would get the htmlwidget rendered without the chunk code as expected.
Now, when I use include = FALSE in the chunks, the htmlwidgets do not get rendered at all.

Here is an example from the networkD3 htmlwidget:

	---
	title: "R Markdown networkD3"
	output: 
	  html_document:
	    toc: true
	---

	## simpleNetwork

	```{r, include=FALSE}
	library(networkD3)
	src <- c("A", "A", "A", "A", "B", "B", "C", "C", "D")
	target <- c("B", "C", "D", "J", "E", "F", "G", "H", "I")
	networkData <- data.frame(src, target)
	simpleNetwork(networkData)
	```

```
R version 3.1.3 (2015-03-09)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.2 (Yosemite)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] htmlwidgets_0.3.3

loaded via a namespace (and not attached):
[1] digest_0.6.8     htmltools_0.2.6  knitr_1.10.5     rmarkdown_0.6.1  rsconnect_0.3.78
[6] tools_3.1.3      yaml_2.1.13  
```

**Comment by jjallaire** [comment]
I think the option you want is echo = FALSE rather than include = FALSE
(include says don't include the output or code of a chunk).

**Comment by jpmarindiaz** [comment]
@jjallaire you are right! 
sorry about the confusion
