### ISSUE TITLE
switch off html escaping

### ISSUE THREAD

**Issue by ThomasSiegmund** [ramnathv/htmlwidgets#118]
Hi,

I need to produce some links in a D3TableFilter widget, but HTML seems to arrive escaped on the JavaScript side. I there a way to avoid this, or do I have to un-escape using JavaScript?

Thanks

Thomas

**Comment by ramnathv** [comment]
Can you post a snippet of the escaped HTML you are getting so that we have more context? I suspect this is connected with a recent change introduced to avoid bugs due to `</script>` tags in the json payload.

**Comment by ThomasSiegmund** [comment]
Hi Ramnath, 

thanks for the quick reply. Can't give you a html snipplet, since the problem is not in the generated html, but in the data arriving at renderValue. See this example:

```r
library(shiny)
library(htmlwidgets)
library(D3TableFilter)

test <- data.frame(URL = c("<a href=http://www.google.com>google.com</a>"))

# ui.R
# --------------------------------------------------------
ui <- shinyUI(fluidPage(
  title = 'Basic usage of D3TableFilter in Shiny',
  fluidRow(
    column(width = 12, d3tfOutput('mtcars'))
  )
))

# server.R
# --------------------------------------------------------
server <- shinyServer(function(input, output, session) {
  output$mtcars <- renderD3tf({
    
    d3tf(test);
  })
  
})

runApp(list(ui=ui,server=server))

```

Thanks

Thomas

**Comment by ThomasSiegmund** [comment]
Never mind, it's documented D3 behaviour. My fault.
