### ISSUE TITLE
Unexpected JS behavior in an HTMLWidget

### ISSUE THREAD

**Issue by zachcp** [ramnathv/htmlwidgets#123]
Hi  Team HTMLWidgets,

Thanks for your great work on this package, its a great addition to the R ecosystem. I've recently started working on an HTMLwidget for the [ChemDoodle WebComponent](http://web.chemdoodle.com/) library, [repo here](https://github.com/zachcp/chemdoodle) and am slowly whipping it into shape except for an error I've encountered where HTML generated from Rmd has unexpected behavior.

Below is an example of chemdoodle's basic functionality: take a SMILES string, parse it and display it on a canvas. If I try to use this in an Rmd document, however, I encounter an error. (gist showing the Rmd, Md, and HTML files [here](https://gist.github.com/zachcp/c995718a5bdf0b9828cb) ) If you open the pandoc-generated HTML in a browser the widget is somehow overriding or erasing the rest of the HTML.  

```[r]
#Basic Example of using Chemdoodle  to draw a molecule
devtools::install_github("zachcp/chemdoodle")
library(chemdoodle)
chemdoodle("C1CCCCNC1") #process and visualize a smiles string
``` 

After a bit more prodding it looks like uncommenting lines 22 or 24 of the HTML file can prevent the problem from happening. These lines initiate HTMLwidgets (22) or are the chemdoodle JS library (24). However, commenting these out result in the loss of the widget. It seems the ChemDoodle Library either generates its canvas when the script is called or it requires a  **canvas** [element with the same id](http://web.chemdoodle.com/tutorial/initializing-canvases) as the webcomponent. So... it looks like the html is being drawn and then Chemdoodle inserts its canvas element and deletes the previous content (I am not sure why).  The two solutions that I am aware of would be to: 

- have HTMLWidgets generate a **canvas** element (instead of a **div**) with the correct ID so that Chemdoodle finds a target and doesn't overwrite anything.
- have HTMLWidgets add the **script** tag at the location/div where you want to create the Chemdoodle Element. Perhaps knitr/Rmarkdown allow that?

Maybe there are other solutions as well? Any suggestions on how to address/handle this behavior would be appreciated.

Thanks, 
zach cp

**Comment by ramnathv** [comment]
@zachcp I will take a closer look later this week, but here are some quick things to get you started.

1. You can generate a `canvas` element instead of a `div`, by following the documentation [here](http://www.htmlwidgets.org/develop_advanced.html#custom-widget-html)

**Comment by jcheng5** [comment]
You should create the canvas element yourself in your inst/htmlwidgets/chemdoodle.js file. I'd change your renderValue to something like this (untested):

```r
    renderValue: function(el, x, instance) {
        var id = this.getId(el);
        // remove any previously created canvas element
        el.innerHTML = "";

        var canvasId = id + "-canvas";
        var canvas = document.createElement("canvas");
        canvas.width = el.offsetWidth;
        canvas.height = el.offsetHeight;
        el.appendChild(canvas);

        //Load And Scale Molecule
        var mol = new ChemDoodle.io.JSONInterpreter().molFrom( x.json );
        mol.scaleToAverageBondLength( x.bondscale );
        //console.log(mol);

        //Create Canvas Element
        var viewercanvas1 = new ChemDoodle.ViewerCanvas(canvasId, x.width, x.height);
        viewercanvas1.specs.bonds_width_2D = 0.6;
        viewercanvas1.specs.bonds_saturationWidth_2D = 0.18;
        viewercanvas1.specs.bonds_hashSpacing_2D = 2.5;
        viewercanvas1.specs.atoms_font_size_2D = 10;
        viewercanvas1.specs.atoms_font_families_2D = ['Helvetica', 'Arial', 'sans-serif'];
        viewercanvas1.specs.atoms_displayTerminalCarbonLabels_2D = true;
        viewercanvas1.loadMolecule(mol);
    }
```

**Comment by zachcp** [comment]
thanks @ramnathv  and @jcheng5 . I'll give this a go tonight. This code is very helpful.

**Comment by timelyportfolio** [comment]
@zachcp I generally go with a route like @jcheng5 suggests, but if you want to see some examples of custom `*_html` functions you can look here.

[metricsgraphics](https://github.com/hrbrmstr/metricsgraphics/blob/master/R/metricsgraphics.R#L615-L618)

**lots of ugly manual html**(I strongly encourage `tags` from `htmltools`) [radialNetwork](https://github.com/timelyportfolio/networkD3/blob/feature/radialNetwork/R/radialNetwork.R#L57-L122)

**Comment by zachcp** [comment]
So I tried @jcheng5 's approach simply modifying  the `var id = this.getID(el)` to `var id = el.id;`

In the html text this leads to the following which I thought would work correctly but does not.
```[html]
<p><div id="htmlwidget-1119" style="width:500px;height:50px;" class="chemdoodle">
<canvas id="htmlwidget-1119-canvas"></canvas>
</div>
<script type="application/json" data-for="htmlwidget-1119">{"x":{"width":500,"height":50,"json":{"b":[{"o":1,"b":0,"e":1},{"o":1,"b":1,"e":2},{"o":1,"b":2,"e":3},{"o":1,"b":3,"e":4},{"o":1,"b":4,"e":5}],"a":[{"x":0,"y":0,"l":"C"},{"x":0,"y":1.5,"l":"C"},{"x":-1.29903810567666,"y":2.25,"l":"C"},{"x":-1.29903810567665,"y":3.75,"l":"C"},{"x":-2.59807621135331,"y":4.50000000000001,"l":"C"},{"x":-2.5980762113533,"y":6.00000000000001,"l":"C"}]},"bondscale":14.4,"backgroundColor":"white","scale":1,"atoms_font_size_2D":12,"atoms_font_families_2D":["Helvetica","Arial","Dialog"],"atoms_font_italic_2D":false,"atoms_circleDiameter_2D":10,"atoms_useJMOLColors":false,"atoms_useJMOLColors.1":false,"atoms_usePYMOLColors":false,"atoms_implicitHydrogens_2D":true,"atoms_displayTerminalCarbonLabels_2D":false,"atoms_displayAllCarbonLabels_2D":false,"bonds_display":true,"bonds_width_2D":1,"bonds_saturationWidth_2D":0.2,"bonds_ends_2D":"round","bonds_useJMOLColors":false,"bonds_usePYMOLColors":false,"bonds_wedgeThickness_2D":0.22,"bonds_hashWidth_2D":1},"evals":[]}</script></p>
<p>Note that the <code>echo = FALSE</code> parameter was added to the code chunk to prevent printing of the R code that generated the plot.</p>
```

I'm going to have a go at @ramnathv and @timelyportfolio 's idea of using htmltools - can the script be called at that site?

 I'll also try to confirm with pure JS that chemdoodle can find and use a tagged canvas as per the docs (I'm pretty sure it can). My guess is that by calling the script at the beginning of the document it interferes with the rest of the drawing. One more thought: would it be possible to serialize the JS as part of the script tag immediately below the DIV/Canvas as is done for the data? That is what I typically have done for static generation using Jinja/Mustache. I'm still a bit unfamiliar with the HTMLWidgets model so I don't have great intuition about the source of the error

**Comment by jcheng5** [comment]
Any idea why the width and height did not get added to the canvas tag?

**Comment by ramnathv** [comment]
Adding the following line to the code by @jcheng5 seems to do the trick for me

```js
canvas.id = canvasId
```

Here is a link to the published html.

**Comment by zachcp** [comment]
@ramnathv fantastic; thank you! Now with a minimal working example I can start to tweak things a bit, add features, etc.
