### ISSUE TITLE
Determining if a widget will be viewed in RStudio's Viewer in my_widget.js

### ISSUE THREAD

**Issue by nsh87** [ramnathv/htmlwidgets#126]
There are some functionalities that don't seem to work when the user is using RStudio's Viewer, but they will work if the widget opens in a browser. For example, if a widget provides the user with an HTML link that opens in a new browser window this obviously works if the widget is being viewed in the browser, but doesn't if the user is viewing the widget in RStudio's Viewer. Can we detect in `my_widget.js` if the user is about to view the widget in RStudio's Viewer so we can respond accordingly in our code (for example by removing those links or including other code to somehow open a browser window)? Apologies if this is already possible. I checked the documentation and didn't find any info on this.

**Comment by jjallaire** [comment]
The viewer adds a "viewer_pane" query parameter that you can test for. e.g. https://github.com/rstudio/dygraphs/blob/master/inst/htmlwidgets/dygraphs.js#L106-L109
