### ISSUE TITLE
file("") only supports open = "w+" and open = "w+b": using the former

### ISSUE THREAD

**Issue by nsh87** [ramnathv/htmlwidgets#128]
Every so often I start getting this warning when `createWidget` runs at the end of my widget's function:

```R
Warning message:
In file(con, "r") :
  file("") only supports open = "w+" and open = "w+b": using the former
```

I think "warning" is a bit misleading, seems more like an error: the widget ends up just being blank because most of my dependencies don't get attached to the HTML when I see this warning - it looks like the only one that gets attached is a dependency I define outside of my widget's `.yaml`. My DOM ends up looking like this:

![screen shot 2015-06-18 at 9 21 16 am](https://cloud.githubusercontent.com/assets/4327717/8236191/9b1ab7f0-159b-11e5-8f29-b2bdf6548d65.png)

When it normally looks like this:

![screen shot 2015-06-18 at 9 25 56 am](https://cloud.githubusercontent.com/assets/4327717/8236292/388d7360-159c-11e5-9c95-d8af186ef86f.png)

I've run a debug and it looks like the error is happening on `createWidget`, but I haven't done further debugging into the function call.

```R
Browse[2]> 
debug at /Users/Nikhil/dev/receptormarker/receptormarker/R/radial_phylo.R
#892: htmlwidgets::createWidget(name = "radial_phylo", x, width = width, 
    height = height, htmlwidgets::sizingPolicy(padding = 22, 
        viewer.suppress = browser, browser.fill = TRUE), package = "receptormarker", 
    dependencies = phyloxml)
Browse[2]> 
exiting from: radial_phylo(tcr, "seqs", verbose = TRUE)
Warning message:
In file(con, "r") :
  file("") only supports open = "w+" and open = "w+b": using the former
> 
```

I can get rid of the error simply by restarting R (RStudio in my case). I don't have any experience with this warning.

**Comment by ramnathv** [comment]
This error usually occurs when some of the paths specified in your dependencies YAML file are not valid paths. The error message you see is returned by one of the base R functions when it is unable to find the file. We could make `createWidget` a bit smarter to do this checks automatically and return a better error message.

If you could point me to your widget's repo, I could help you locate the error.

**Comment by nsh87** [comment]
Sure thing. My widget is here: https://github.com/nsh87/receptormarker/tree/radial_phylo_htmlwidget/inst.

Is there any reason why the error only occurs once in a blue moon?

**Comment by ramnathv** [comment]
I don't see `createWidget` in your R code. Can you point me to the portion where you are defining your widget?

**Comment by nsh87** [comment]
Absolutely: https://github.com/nsh87/receptormarker/blob/radial_phylo_htmlwidget/R/radial_phylo.R#L894.

**Comment by timelyportfolio** [comment]
I get this with devtools::load_all .  If I do devtools::install all works fine.

**Comment by timelyportfolio** [comment]
Also if you are interested I had done some experimental phylo work in a forked branch of networkD3 https://github.com/timelyportfolio/networkD3/tree/feature/phylogram and http://bl.ocks.org/timelyportfolio/59acc3853b02e47e0dfc.  Also there is this http://www.buildingwidgets.com/blog/2015/2/26/week-08-interactive-phylogeny.

**Comment by nsh87** [comment]
Thanks @timelyportfolio, I will try for a while with `devtools::install()` only.

That's all pretty cool stuff with the phylogenies, thanks for sharing! Pretty surprised to hear that htmlwidgets for phylogenies is one of the top requests. Phylogenies are a bit of a misnomer for what this package is intended for, which is analysis antibody/T-cell receptor sequences and function, which don't have any evolutionary relationship. We're just using multiple sequence alignment to explore the similarities/differences in the protein sequences that define the antibody receptor's shape and what it responds to. What's most useful for that type of analysis is to visualize the sequence along with some info about each cell's phenotype. I use [JSPhyloSVG](http://www.jsphylosvg.com) in order to get some pretty cool (and surprisingly useful) radial phylograms like this:

![screen shot 2015-06-18 at 12 15 57 pm](https://cloud.githubusercontent.com/assets/4327717/8239919/d8ab72cc-15b3-11e5-89a8-a444d51f0f21.png)

So we can incorporate a ton of information into these phylograms and then pretty quickly learn about an immune response. Now if only I could make nodes collapse....that's a task for v2 I think. I'll check out more of the links you provided.

**Comment by ramnathv** [comment]
I can help with making the nodes collapse :) Let me take a look at the JS code to see how difficult it is.

**Comment by nsh87** [comment]
Hah, awesome! I think that would warrant a fork of the JSPhyloSVG project, which seems to have been abandoned so someone copied the code onto GitHub here https://github.com/guyleonard/jsPhyloSVG. I've only made some minor changes to the original JS code and it looked pretty complex when I went in there, although I haven't really scoped it out much.

**Comment by nsh87** [comment]
Not sure why it was abandoned since it is an extremely awesome library with a ton of potential.

**Comment by ramnathv** [comment]
Well, it uses `raphael.js`. I was hoping it uses `d3` which would have made it easier to add the collapse option.

**Comment by nsh87** [comment]
Ah, yes, that is no small detail.

**Comment by ramnathv** [comment]
It is a fair bit of work, but with D3 it would have been manageable.

**Comment by nsh87** [comment]
Maybe that's why they stop developing it. Raphael doesn't seem to have a lot of traction even though it is still being versioned. One can't argue with D3's prowess.

**Comment by ramnathv** [comment]
I am closing this issue. More discussions around widgets for phylogenies can be carried out in the relevant repos like the one created by @nsh87
