### ISSUE TITLE
Nested Tree Map?

### ISSUE THREAD

**Issue by ignacio82** [ramnathv/htmlwidgets#133]
Any plans to implement [this](http://d3plus.org/examples/advanced/9860719/) or something similar?

Thanks!

**Comment by timelyportfolio** [comment]
I think a treemap would fit nicely in `networkD3` by @christophergandrud.  Here is some early work I put in towards that effort http://www.buildingwidgets.com/blog/2015/1/23/week-03-more-network-layouts.

At one point, I know @ramnathv had put some effort into a `d3plus` widget.  He also might have a prototype implementation.

**Comment by christophergandrud** [comment]
That would fit in well with networkD3.

**Comment by ignacio82** [comment]
@christophergandrud should I  create a feature request in the github for networkD3? Thanks!

**Comment by christophergandrud** [comment]
Sure. A pull request would be even better!

**Comment by ignacio82** [comment]
Never done a pull request, no clue how to do one :_(

**Comment by ramnathv** [comment]
I am closing this issue. You can continue the conversation on `d3Network`.
