### ISSUE TITLE
New widget request: Parallel Coordinates in htmlwidgets?

### ISSUE THREAD

**Issue by talgalili** [ramnathv/htmlwidgets#142]
I came across this library:
http://syntagmatic.github.io/parallel-coordinates/

Any chance to get it, or something similar, in htmlwidgets?

Thanks!

**Comment by timelyportfolio** [comment]
Yes https://github.com/timelyportfolio/parcoords is a pretty good start.  Would love feedback.  See post http://www.buildingwidgets.com/blog/2015/1/30/week-04-interactive-parallel-coordinates-1 for some discussion and details.

**Comment by talgalili** [comment]
Perfect, thanks!
