### ISSUE TITLE
HTMLWidgets don't show in RMD if they are in an if statement and have code executed after them in the same chunk.

### ISSUE THREAD

**Issue by alexcritschristoph** [ramnathv/htmlwidgets#147]
The title is pretty descriptive of this bug.. I don't think this is widget specific, I've replicated it with multiple widgets, always with the same result. Issue is with both knit() and knit2html().

Here's the reproducible example: (save as an Rmd file, and then run knit() or knit2html() on it)

```
---
title: "HTMLWidgets Bug"
output: html_document
---

```{r exampleChunk, results='asis'}
library(ggplot2)
test = TRUE
library(DT)
data(mtcars)

if (test) {

  datatable(mtcars)

  test = 1
}```
```
- - - - - -

The HTMLWidget will not be in the markdown generated by knit() or knit2html(). 
Now, remove the if statement or remove the test = 1. The HTMLWidget will be in the markdown. Using print or show on the HTML widget does not change this behavior. Setting results to any of the options for the code chunk does not change this behavior.

**Comment by alexcritschristoph** [comment]
Package version: 0.5. R version: 3.2.1. knitr version: 1.10.5.

**Comment by jcheng5** [comment]
This is "by design". Don't think of `datatable(mtcars)` as being a command to output a datatable, but rather a call that returns a datatable object. Think of this as an analog:

```
```{r}
if (test) {
  mtcars
  test = 1
}
```

Would you expect mtcars to be printed? (Hopefully not.) Similarly, the datatable will not be printed unless it is returned to the top level:

```
```{r}
if (test) {
  dt <- datatable(mtcars)
  test = 1
  dt
}
