### ISSUE TITLE
In JS bindings, resize() can't call renderValue()

### ISSUE THREAD

**Issue by jcheng5** [ramnathv/htmlwidgets#151]
For bindings that want to re-render on resize, we'd like this to work:

```r
renderValue: function(el, x, instance) {
  instance.lastValue = x;
  // render...
},
resize: function(el, width, height, instance) {
  this.renderValue(el, instance.lastValue, instance);
},
```

This doesn't work today because `this.renderValue()` doesn't call the `renderValue` right in front of you, but a monkeypatched version that htmlwidgets inserts on your behalf when you register the widget. The monkeypatched version expects not an `x` value but `data`, from which it retrieves `x`:

https://github.com/ramnathv/htmlwidgets/blob/a8276d4378e5bb8603b24a9b7aac617bed2b11c4/inst/www/htmlwidgets.js#L413

This should be fixed by not using the monkeypatching approach for Shiny bindings, but rather, decorator. In other words, the Shiny binding should be a wrapper around the htmlwidget binding, instead of taking the htmlwidget binding and monkeypatching it into a Shiny binding. (Boy, it seems pretty obvious when I put it that way...)

**Comment by ramnathv** [comment]
Interesting observations @jcheng5. Based on the comment, seems like you are already well on your way to figuring out the solution. Do you want any of use to do something about this prior to that? Let us know.

**Comment by jcheng5** [comment]
Yeah the solution is simple. I just need time to type it in carefully and test. :)

**Comment by ramnathv** [comment]
Great. Let me know if you need a hand testing.
