### ISSUE TITLE
Minor problem in Introduction vignette

### ISSUE THREAD

**Issue by dmurdoch** [ramnathv/htmlwidgets#152]
I noticed a minor problem in the Demo section of the Introduction vignette. You say:

"Our widget is now complete! If you want to test drive it without reproducing all of the code locally you can install it from GitHub as follows:

    devtools::install_github('jjallaire/sigma')

You can also download the ediaspora.gexf.xml file and place it in the directory inst/htmlwidgets/examples."

The problem is that `install_github()` will have installed the package and not kept the source, so we don't get a source dir to put the example data in. It needs to go into "examples/ediaspora.gexf.xml" in `system.file("htmlwidgets", package="sigma")`, or just some user directory (and then instructions for accessing it would need modification).

**Comment by jjallaire** [comment]
Fixed via https://github.com/ramnathv/htmlwidgets/commit/a37efa3f716377b1b1f5fcc306eafa058cc2a92e

I think the whole reference to downloading the sample data is confusing so I removed it wholesale.
