### ISSUE TITLE
widget SVG onclick support issue in RStudio viewer

### ISSUE THREAD

**Issue by skyebend** [ramnathv/htmlwidgets#153]
I'm finding a strange issue where the onclick event attached to an SVG element in htmlWidget is not triggered in the RStudio viewer, but works fine in other browsers (including Chromium, which I think is also webkit?)

When this knitr document is viewed in RStudio

https://csde.washington.edu/~skyebend/RmarkdownWidgetTest.html

the 'play' button for the animation doesn't work when the triangle is directly clicked, but it does work when clicked slightly below, on the containing div.  It also works when I disable pointer events on the svg icons with ```.controls svg { pointer-events: none; }``` (but then mouseover highlighting obviously doesn't work)

Not sure how I can provide testing code until I deploy the new version of the ndtv package to CRAN.  Is there a known browser that is similar to the RStudio viewer I can debug the widget in?  Any ideas why the svg might eat the onclick event in RStudio only? 

This occurs on ubuntu
Version 0.99.473 – © 2009-2015 RStudio, Inc.
Mozilla/5.0 (X11; Linux i686) AppleWebKit/538.1 (KHTML, like Gecko) RStudio Safari/538.1 Qt/5.4.0

**Comment by ramnathv** [comment]
Here is what the RStudio viewer uses. Can you post some reproducible code, that will enable us to replicate this issue within RStudio?

```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.78.2 (KHTML, like Gecko)
```

**Comment by skyebend** [comment]
install draft version of the package from https://csde.washington.edu/~skyebend/ndtv_0.7.tar.gz

then run

```{r}
library(ndtv)
data(short.stergm.sim)
render.d3movie(short.stergm.sim,output.mode='htmlWidget')
```

**Comment by jjallaire** [comment]
Note that for debugging you can also right click the global toolbar in
RStudio and then click the "Inspect" menu to get the standard suite of
WebKit developer tools.


On Tue, Sep 1, 2015 at 8:12 PM, Skye Bender-deMoll <notifications@github.com

**Comment by skyebend** [comment]
Thanks for the invaluable tip on how to access the debugger.  I can now see that d3 is giving an Error "TypeError: undefined is not a function (evaluating 'e.getAttribute("class")')" when the click target is the svg path ('SVGElementInstance') instead of 'svg' or 'div'.   I'll dig into it further

**Comment by skyebend** [comment]
we were able to fix this by changing  event.target to event.currentTarget in one of the conditionals being tested using the d3 classed function.  This was not an htmlWidgets issue at all

**Comment by jjallaire** [comment]
@hafen Might this be similar to the issue you are seeing in rbokeh?
