### ISSUE TITLE
sigma example is still confusing 

### ISSUE THREAD

**Issue by ziyadsaeed** [ramnathv/htmlwidgets#156]
In "how to create your own widget" using sigma.js. You should mention how the javascript that sigma.js wants was created by your function. For eg on sigma.js site they have an example of how to use sigma using the following js.
```Javascript
<script>
  sigma.parsers.json('data.json', {
    container: 'container',
    settings: {
      defaultNodeColor: '#ec5148'
    }
  });
</script>
```
It still isn't clear to me how was this script generated in renderValue function.

**Comment by jcheng5** [comment]
Looks like it's using `sigma.parsers.gefx` instead, it looks pretty clear to me...?

**Comment by ziyadsaeed** [comment]
I'm not talking about sigma.parsers.gefx.
I'm unable to connect these two parts
 "This is __what__ the js the widgets wants" and "This is __how__ to generate that js"

**Comment by ramnathv** [comment]
Well, you need to understand how `sigma.js` works before plugging it into `htmlwidgets`. In this case, the connection is the documentation for the [sigma.parsers.gexf](https://github.com/jacomyal/sigma.js/tree/master/plugins/sigma.parsers.gexf) plugin.

**Comment by timelyportfolio** [comment]
Perhaps, we can take a different approach.  @ziyadsaeed what library would you like to wrap as an `htmlwidget` and I'll volunteer to help walk you through creation.   Then, maybe we can create a tutorial  around what we did.
