### ISSUE TITLE
Get back in R some data modified in javascript ?

### ISSUE THREAD

**Issue by bthieurmel** [ramnathv/htmlwidgets#157]
Hi,

is-there a way to get back in R an object / variable, first send to javascript and modified ?

Thanks

**Comment by ramnathv** [comment]
Are you talking about sending data back from the client (javascript) to the server (R) in the context of a `shiny` application?

**Comment by bthieurmel** [comment]
Yes, thanks, I know the cool ```Shiny.inInputChange``` in a shiny context, but it-is possible also only in a "rstudio" context ? Perhaps it's a little bit a strange / stupid question ...! (In my case, people can editing data using javscript library, and want to get back this information in R)

**Comment by ramnathv** [comment]
Can you elaborate on what you mean by 

> but it-is possible also only in a "rstudio" context ? 

`Shiny.onInputChange` will work outside of RStudio.

It would be good if you can provide a concrete example of what you are trying to do here, so that we can point you to the right solution.

**Comment by bthieurmel** [comment]
In our package ````visNetwork````, people can editing data and so network dynamically with javascript option. Here is a simple example : 

````
nodes <- data.frame(id = 1:3)
edges <- data.frame(from = c(1,2), to = c(1,3))

# directed network
visNetwork(nodes, edges) %>%
  visOptions(manipulation = TRUE)
````

Some people ask us if it's possible to get back modified data in R, after editing, and without use shiny....

**Comment by ramnathv** [comment]
To achieve this dynamically, you would need a connection between the browser and R, at the very least. Shiny is the easiest way to achieve this. You might be able to do something with `Rserve` or a similar package, but one will have to investigate those options.

A simple solution would be to let the user download the modified data as json, which can then be read back into an R session.

**Comment by jcheng5** [comment]
Shiny is absolutely perfect for this scenario (building tools to be used in RStudio), why can't you use it? If you don't use Shiny, you'll end up building your own framework that does exactly the same thing.

https://stackoverflow.com/questions/27365575/how-to-exit-a-shiny-app-and-return-a-value
https://github.com/jcheng5/ggutils

**Comment by bthieurmel** [comment]
I'm totally agree with you, shiny is perfect for this scenario. it's not me but a ````visNetwork```` user who ask if it'll be possible to do that without shiny... 
I'm going to propose a shiny answer.
Thanks.
