### ISSUE TITLE
data reordered when passed to widget

### ISSUE THREAD

**Issue by jrowen** [ramnathv/htmlwidgets#158]
This issue originated with https://github.com/jrowen/rhandsontable/issues/47.  In the example below, the column order changes when shown in the widget.
```
library(dplyr)
library(tidyr)
library(rhandsontable) 

mtcars %>% 
  group_by(vs, cyl) %>% 
  summarise(num = n()) %>% 
  spread(cyl, num) %>% 
  rhandsontable()
```
In `application/json` for the widget shown in the html source, the data is in the correct order.
```
"data":[{"vs":0,"4":1,"6":3,"8":14},{"vs":1,"4":10,"6":4,"8":"NA"}]
```
Adding a breakpoint at line 18 of `rhandsontable.js` shows `x.data` with a different order.
```
> x.data
<-[Object
4: 1
6: 3
8: 14
vs: 0
__proto__: Object, 
Object
4: 10
6: 4
8: "NA"
vs: 1
__proto__: Object]
```
Since the order is correct in the list passed to `htmlwidgets::createWidget` (and in the html source), it would appear that a step in the `createWidget` process is reordering the data (reordering seems to follow `sort(colnames)`).

**Comment by timelyportfolio** [comment]
The data is being passed correctly to `HTML/JS`, and it appears the `toArray` is causing the trouble.  I'll explore a little further and report back.

**Comment by timelyportfolio** [comment]
I think safe to close here.  I'll respond with the solution over on `rhandsontable` https://github.com/jrowen/rhandsontable/issues/47.
