### ISSUE TITLE
Utilise sendCustomMessage to update js

### ISSUE THREAD

**Issue by andy-law** [ramnathv/htmlwidgets#174]
I'm trying at the moment to make updates via `session$sendCustomMessage` and `Shiny.addCustomMessageHandler` work for a htmlwidget. The issue that I'm currently having is that one of the values that I'm passing to javascript is wrapped in the `JS()` function on the Shiny side, which should be evaluated as a function within javascript. However, the value is currently being interpreted as a function in javascript. See code below for example:
In Shiny:
```
session$sendCustomMessage(type = "updateMyComponent", list(id=inputId, data=list(choices = choices, format = JS("function(value) { return value.foo + ' ' + value.bar; }") )
```

In JS:
```
Shiny.addCustomMessageHandler('updateMyComponent', function(handlerData) {
    console.log(handlerData.data.format); // function(value) { return value.foo + ' ' + value.bar; }
    console.log(typeof handlerData.data.format); //string
});
```
Is there any way to enforce that the javascript interprets the value as a function rather than a string?

**Comment by ramnathv** [comment]
Why not just send  `value` to the client and then move the `format` function to the client side? AFAIK, `sendCustomMessage` serializes any R objects to JSON and functions are not serializable. @jcheng5 might be able to add more here.

**Comment by andy-law** [comment]
The reason for keeping this on the Shiny side is that I'm working on a library for data scientists to implement visualisations without having to step into the HTML/JS world. This means that without stepping into the JS, the user should be able to format a string value from a . 
It seems like `createWidget` does something to convert JS() wrapped options into functions on the client, but I'm unable to see how to trigger this myself or how the client goes about detecting that it should convert a value to a function.

**Comment by ramnathv** [comment]
You can `eval` the string and treat it as a function. Note that using `eval` in general is a bad idea, especially if you are letting the end-user specify a function as a string, since you are now exposing your application to the risk of arbitrary code injection.

```js
Shiny.addCustomMessageHandler('updateMyComponent', function(handlerData) {
    var format = eval("(" + handlerData.data.format + ")")
    console.log(typeof format)
});
```

**Comment by andy-law** [comment]
Yes, thought about that as an option, but as you say it's not great due to security concerns. However, as this is for an internal product, perhaps it's the easiest way to go for this one. Thanks for your help @ramnathv

**Comment by ramnathv** [comment]
Glad to be of help. Closing this issue.

**Comment by jcheng5** [comment]
That's essentially what htmlwidgets does with JS() anyway, so the security concerns would be about the same whether you do the eval() or we do. In either case it's VERY important to ensure that the JavaScript code comes from a trustworthy source.
