### ISSUE TITLE
output standalone HTMLWidgets using command-line knitr

### ISSUE THREAD

**Issue by zachcp** [ramnathv/htmlwidgets#182]
Hi Team HTMLWidgets,

I have a question about how to output fully-functional HTMLwidgets to Markdown. My use case is a blog situation where I would like to convert Rmarkdown to markdown and the static blog generator then does what it does - adding headers and such. Right now I am calling knitr, via Make, like so:

```{r}
content/blog/blog1.md: R/blog1.Rmd
    Rscript -e \
    'library(knitr); \
     opts_knit$$set(unnamed.chunk.label="blog1-1", \
                    base.dir="static/pics/R", \
                    base.url="/pics/R/"); \
     knit("$<", output="$@")'
```

The output, however, does not include the JS needed to render. Is there a way to flag the `standalone=True` from the command line?

Thanks!
zach cp

**Comment by jjallaire** [comment]
htmlwidgets require that the environment generating the HTML be
widget-aware so knitr by itself won't be enough.;

I'd recommend that you call htmlwidgets::saveWidget(w, selfcontained =
FALSE) and then incorporate the generated HTML (both <head> tags and <div>
with the widget) into your blog.

**Comment by zachcp** [comment]
thanks for the recommendation @jjallaire
