### ISSUE TITLE
Allow access to object returned by renderValue

### ISSUE THREAD

**Issue by ramnathv** [ramnathv/htmlwidgets#19]
The basic idea here (thanks @timelyportfolio) is to provide users a mechanism to access the return value of `renderValue` so that users can inject additional behavior using javascript. Since all instances of a widget have a unique id and this is accessible to `renderValue`, I believe we can use the `id` as key to identify the widget.

The easiest way to do this probably is to create a `HTMLWidgets.obj` object and push the output of `renderValue` with the widget id as key. 

@jcheng5 @jjallaire Your thoughts on this? If the implementation is easy, I think it makes sense to do this as it will open up a wider range of use cases.

**Comment by jcheng5** [comment]
I think we can close this, right? Because we have `onRender` and `onStaticRenderComplete`?

**Comment by timelyportfolio** [comment]
Would agree can close this.

**Comment by timelyportfolio** [comment]
didn't mean to close, I'll let y'all decide.  Pushed the wrong button.

**Comment by timelyportfolio** [comment]
going to close since no other comments or objections
