### ISSUE TITLE
scaffoldWidget return error on Windows 10

### ISSUE THREAD

**Issue by kasper2619** [ramnathv/htmlwidgets#196]
Hi.

First of all thank you for providing these cool functionalities the htmlwidgets package provides. The ability to couple R, Shiny, and Javascript is the last functionality I need to create some really awesome analytics apps that I have been wanting to do for years.

However, I am occuring what seems to be a Windows 10 bug.

The code below works on my Windows 7 machine but not my Windows 10 machine:

```
# libpath
.libPaths("C:/R/R-3.2.4revised/library")

library(htmlwidgets)
library(devtools)

# need to be something in the package
placeholder <- function(x, y) x+y

# generate package
package.skeleton(name = "mywidget", list = c("placeholder"),
                 environment = .GlobalEnv,
                 path = ".", force = FALSE,
                 code_files = character())


# package dir
path <- "C:/Users/kaspe/Desktop/R/practise/htmlWidgets/mywidget"


#devtools::create("mywidget")               # create package using devtools
setwd(path)                          # navigate to package dir
htmlwidgets::scaffoldWidget("mywidget")    # create widget scaffolding
devtools::install()
```

When I am running the command:
`> htmlwidgets::scaffoldWidget("mywidget")    # create widget scaffolding`

It produces the following error:
```
Created boilerplate for widget constructor R/mywidget.R
Error in editor(file = file, title = title) : 
  argument "name" is missing, with no default
```

Best
Kasper

**Comment by kasper2619** [comment]
For som reason it worked to set `edit = FALSE` in the scaffoldWidget function. See question on stackoverflow.

[http://stackoverflow.com/questions/36250023/how-to-get-r-htmlwidgets-to-work-on-windows-10-machine?noredirect=1#comment60130161_36250023]

**Comment by ramnathv** [comment]
Interesting. I will check what could be happening here.
