### ISSUE TITLE
Documentation has wrong vignette names?

### ISSUE THREAD

**Issue by maptracker** [ramnathv/htmlwidgets#198]
The documentation invites the user to explore the three vignettes:

```R
vignette("htmlwidgets-intro")
vignette("htmlwidgets-sizing")
vignette("htmlwidgets-advanced")
```

... but they appear to be registered in my installation (0.6) as:

```
develop_advanced        Advanced (source, html)
develop_intro           Introduction (source, html)
develop_sizing          Sizing (source, html)
```
I can access them using those names, but not those referenced in the documentation.

**Comment by jjallaire** [comment]
Thanks! Fixed here: https://github.com/ramnathv/htmlwidgets/commit/34d9cd02cc04805b3f8b79f0703b8770db9e486d
