### ISSUE TITLE
size changed detection

### ISSUE THREAD

**Issue by jjallaire** [ramnathv/htmlwidgets#200]
In working on flexdashboard I noticed that dygraphs were not resizing when the flexbox layout changed (no idea why). To overcome this I wrote the following simple jquery plugin:

https://github.com/rstudio/dygraphs/blob/master/inst/htmlwidgets/dygraphs.js#L24-L42

Then use it in dygraphs here:

https://github.com/rstudio/dygraphs/blob/master/inst/htmlwidgets/dygraphs.js#L159-L164

I don't know how widespread this issue will be, but it occurs to me that we could implement this in htmlwidgets and make it an opt-in feature (disabled by default)

What does everyone think?

**Comment by ramnathv** [comment]
So @jjallaire this plugin basically triggers the `resizeHandler` when the parent element's width or height changes?

**Comment by jjallaire** [comment]
Yes, whenever the containing el changes size it calls the resizeHandler.

**Comment by ramnathv** [comment]
I like the idea. And I agree that we should make it opt-in, since some widget authors might want to have more control on how things happen. We should also investigate a plain vanilla equivalent so that non jquery based widgets can also take advantage of this. But, we don't need to wait to merge a PR based on this.

**Comment by jjallaire** [comment]
Okay, I'll put together a PR that doesn't use query. Will also make it
opt-in as discussed

**Comment by jjallaire** [comment]
I was attempting to reconstruct the original problem I had with dygraphs
(as an illustration/testbed) but I can no longer repro the problem. I'd
rather wait until I have a repro with dygraphs (or someone else with
another widget) so we can reason better about what's going on and what the
right solution is. So putting this on hold for now....

**Comment by jcheng5** [comment]
(I agree we should put this on hold until we have a repro case but jotting down my thoughts now so I don't lose them in case that time comes)

The master branch of dygraphs has had more commits so I'm not 100% sure of the code you're talking about but I assume it's this? https://github.com/rstudio/dygraphs/commit/7c202486fbb8248db8a9ca2c846ac409cd0da8bb

I don't love the idea of every widget having its own `setInterval(100)` just on the off chance that you do something that affects something. Maybe we could consider a heuristic like only checking when a keyup or mouseup event occurs, and throttling the checks so they don't happen more than every 100 milliseconds.

**Comment by jjallaire** [comment]
That's the one. I removed it for the time being so that I can find the
repro again!

I agree about all the widgets not having their own timer, my thought was
that if this is in some way necessary for a subset of widgets then we could
have a central facility that widgets could opt in to (rather than everyone
copy/pasting my dygraphs hack).

I'm hopeful though that this is idiosyncratic to dygraphs (which does seem
to have more size oriented problems than other widgets). Another
possibility is that it's flexbox bugginess in one of the browser
implementations which we'd also expect to go away over time.

**Comment by jcheng5** [comment]
@jjallaire Just to make sure I understand, are there situations in flexdashboard that will cause a widget's size to change besides 1) resizing the browser, or 2) Bootstrap tab/nav bars?

**Comment by jjallaire** [comment]
It seems there were (but again I can't repro offhand so I can't confirm the
exact scenario). I am going to put a bunch more time into flexdashboard
soon and I'll make sure to use dygraphs in my demo code so I find the issue
again.

**Comment by jjallaire** [comment]
Okay, I have the repro for this now, it was the combination of flexdashboard and `runtime: shiny`:

First install the current versions of **dygraphs** from GitHub (it has the size changed polling removed):

```r
devtools::install_github("rstudio/dygraphs")
```

Then try this Rmd:

    ---
    runtime: shiny
    output: flexdashboard::flex_dashboard
    ---

    ### Dygraph

    ```{r}
    library(dygraphs)
    dygraph(ldeaths)
    ```

The dygraph comes up not sized to the container (it then takes a browser resize or the polling hack to get it to size itself into it's container).

So there may be something we can do that isn't size changed polling to overcome this, but I'm not sure what that would be. @jcheng5 let me know what you think.

**Comment by jcheng5** [comment]
@jjallaire I'm seeing something different. At width < 768px it doesn't fill up the page. At 768px or greater, it does. (And when it crosses the threshold it appears to reload the page--I assume that's intentional flexdashboard behavior?)

**Comment by jcheng5** [comment]
@jjallaire Wait, I get the repro now. It's not consistent, it seems to help if I restart the R session before launching the document (weirdly).

**Comment by jcheng5** [comment]
@jjallaire It feels to me like there's a race condition between when the dygraph loads, and when flexdashboard finishes messing with the DOM. I tried to put this line:

```javascript
$("#dashboard-container").trigger("shown");
```

in flexdashboard.js after all the layout work is done, but I couldn't figure out where that might be (there are a couple of setTimeouts). If I run the above code in a `setTimeout(..., 20)` at the beginning of your `componentLayout` function the problem seems to be resolved, but I have no idea if that's the right place for it.

**Comment by jjallaire** [comment]
Excellent! This makes complete sense.

It looks like this issue is confined to static renderings of htmlwidgets
within runtime: shiny (reactive widget output works fine as you'd expect).

My fix is to trigger shown 200ms after flexdashboard layout is complete:

https://github.com/rstudio/flexdashboard/commit/956f3471c1c3fb4cae95e22f0ed93c388c26ecff

In my experience 100ms worked fine but 50ms still had issues (some resizing
occurred but the x-axis was still offscreen for dygraphs). To be
conservative I used 200ms. I obviously don't love this as for some systems
this could still fail but I don't know what else could be done to make
things more deterministic.

**Comment by jcheng5** [comment]
Great!
