### ISSUE TITLE
htmlwidget grid funcionality

### ISSUE THREAD

**Issue by jbkunst** [ramnathv/htmlwidgets#201]
Hi all!

I open this issue to discuss the implementation fo a grid funcionality inspired by [mjs_grid](https://github.com/hrbrmstr/metricsgraphics/blob/master/R/mjs_grid.R). I implemented a more little sophisticated function base on [simple-grid](http://thisisdallas.github.io/Simple-Grid/) so the grid is fluid and responsive and simulate `facet_wrap`. You can see a example [here](http://rpubs.com/jbkunst/169407)

this worth to add in htmlwidgets? 

*I know htmlwidgets is for create widgets, but don't have sense each package/widget have their own grid funcionality*.

**Comment by ramnathv** [comment]
The idea is neat! However, I would rather not tie implementations to a specific framework since there are so many different ways to layout widgets in a grid. This would make for a really slick package that enhances `htmlwidgets`.

**Comment by hafen** [comment]
Agree that this is cool and would be a nice capability to have for any htmlwidget, potentially as its own package ("widgetgrid"?).  There are a lot of considerations for putting widgets in grids, such as axis limits, shared axes, etc.

FWIW, an existing capability for putting widgets (or any other R plot output) in a grid is [Trelliscope](http://tessera.io/docs-trelliscope/).  Beyond a grid, it allows a way to deal with potentially millions of grid panels and provides the ability to sort / filter / navigate the panels.  I'm working on a pure JS version and a simplified interface, but here's the leaflet example in Trelliscope.

```r
install.packages("trelliscope")
library(leaflet)
library(rvest)
library(purrr)
library(dplyr)
library(trelliscope)

dat <- read_html("http://www.geonames.org/AU/largest-cities-in-australia.html") %>% 
  html_table(fill = TRUE) %>% .[[2]]
coords <- strsplit(dat[["Latitude/Longitude"]], " / ") %>%
  map(~ data_frame(lat = as.numeric(.[1]), lon = as.numeric(.[2]))) %>%
  rbind_all()
citystate <- strsplit(dat[[2]], "  , ") %>%
  map(~ data_frame(city = .[1], state = .[2])) %>%
  rbind_all()
mapdf <- cbind(coords, citystate)
mapdf$pop <- as.numeric(gsub(",", "", dat$Population))

vdbConn(tempfile(), autoYes = TRUE)
divide(mapdf, by = c("city", "state")) %>%
  makeDisplay(name = "aus_cities",
    panelFn = function(x) {
      leaflet() %>%
        addTiles() %>% 
        addMarkers(lng = x$lon, lat = x$lat, popup = getSplitVar(x, "city"))
    },
    cogFn = function(x)
      list(pop = cog(x$pop, desc = "population")),
    state = stateSpec(
      layout = list(nrow = 2, ncol = 3),
      labels = c("city", "state", "pop")))

view("aus_cities")
```

**Comment by jbkunst** [comment]
Thanks @ramnathv @hafen for your insights, helps a lot.

Nice package trelliscope ultra powerful. I was thinking in a more humble/simple grid interface :sweat_smile: 

Cheer,
