### ISSUE TITLE
bower.json

### ISSUE THREAD

**Issue by xizhiming** [ramnathv/htmlwidgets#204]
htmlwidgets/R/scaffold.R  
>> I have a problem with function readBower:
readBower <- function(pkg, src = "inst/htmlwidgets/lib"){
  bower = jsonlite::fromJSON(
    file.path(src, pkg, '**# bower.json**')

When I excute "bower install jquery" ,I don't find file "bower.json" , I just find file "package.json"

**Comment by timelyportfolio** [comment]
This [discussion](https://github.com/bower/bower/issues/859) might help.  If you need `jQuery` though, I would recommend leveraging `rmarkdown::html_dependency_jquery()`.  Or you could just copy/paste the `jQuery` css/js in the correct place.  See [DT](https://github.com/rstudio/DT/tree/master/inst/htmlwidgets/lib/jquery) as an example.

**Comment by xizhiming** [comment]
thank you !   I used the second solution that you said and solved the problem.
