### ISSUE TITLE
Converting flat dataframe to nested json or nested lists

### ISSUE THREAD

**Issue by jto888** [ramnathv/htmlwidgets#206]
In my FaultTree project the hierarchy tree data is assembled in a dataframe. Each row represents a node. Each node has a uniquely assigned ID represented in a column with that name. Nesting is indicated by a Parent column listing the ID of the parent node. (A negative value is used for the root parent.)
I understand that this is  common representation, and have seen tutorials in the .Net world for building the nested json from such a flat file. 
My question is, has anyone seen this done before in R? (I have looked and cannot find.)
If not, is there interest in reviewing my formative solution and generating a more robust and generalized version.
In order for me to experience initial success with bringing my FaultTree to htmlwidget status I had to take my json and convert back to nested list using jasonlite::fromJason as Christopher Gandrud demonstrates on his networkD3 page. I am struggling with a means of generating the nested lists directly from the flat dataframe.

**Comment by timelyportfolio** [comment]
You are correct; this is a very common problem.  For me,  using `data.tree` has been the easiest solution.  See http://stackoverflow.com/questions/31339805/converting-json-format-to-csv-to-upload-data-table-in-r-to-produce-d3-bubble-cha/31352770#31352770 and http://stackoverflow.com/questions/31339805/converting-json-format-to-csv-to-upload-data-table-in-r-to-produce-d3-bubble-cha/31425323#31425323.  `d3 v4` new hierarchy methods will allow a flat file representation, so once it is released perhaps our lives become much easier.  I'll try to take a look at `FaultTree` to see if I can make any suggestions.

**Comment by jto888** [comment]
Yes, Christoph has provided a good example of using 
data.tree::fromDataFrameNetwork(df) in response to my raised issue #68 
on gluc/data.tree I will follow up on this in a branch of 
FaultTree.widget, but I do not expect to use this. Currently the 
conversion of my json to the nested list required by htmlwidgets by use 
of jsonlite is acceptable. The only thing better might be for 
htmlwidgets to take the json string as a list item directly.

There is another reason that I like to maintain restrictive control of 
dependencies in my code. I view my developments in R to be potential 
prototypes for application code that may be later developed on other 
platforms. Such as PHP  or Node on server-side, or even C++ functions 
called from PHP, or C# used with .Net framework. I have also used rserve 
when dependency requires R on server-side, but this too is rather viewed 
as a prototyping step, than a final robust solution. Yes, I am familiar 
with Shiny.

I have begun to document the development of my json builder (ftree2json) 
into a more robust and general solution within FaultTree under 
jto888/FaultTree/issues. This discussion should move to that location.  
It would be my pleasure to see this function turned into something 
available in a package dedicated to manipulating flat file trees, but I 
must proceed.

**Comment by jto888** [comment]
I have pulled a version 0.0.6 to github/jto888/FaultTree, which now includes a generalized and robust function hierarcyDF2json. I  hope this helps others.
