### ISSUE TITLE
Error after following "creating a widget" tutorial

### ISSUE THREAD

**Issue by tbadams0405** [ramnathv/htmlwidgets#207]
Hi there,

I'm attempting to follow the [creating a widget article](http://www.htmlwidgets.org/develop_intro.html) to develop an htmlwidget for a very basic javascript library of one function I have written. I copy and pasted the following lines to create a widget scaffold:

`devtools::create("mywidget")`
`setwd("mywidget")`
`htmlwidgets::scaffoldWidget("mywidget")`
`devtools::install()`

and then these to test out the scaffold:

`library(mywidget)`
`mywidget("hello, world")`.

However, I'm receiving an error. 
"Error in dirname(to) : a character vector argument expected
In addition: Warning message:
In file(con, "r") :
  file("") only supports open = "w+" and open = "w+b": using the former"

I am also receiving this same error when I am trying to run the htmlwidget I have created. Any ideas on why I would be seeing this error? My understanding is I would just get an echo back from this basic helloworld htmlwidget.

**Comment by timelyportfolio** [comment]
Interesting...  If you cross post, please notify and refer -- http://stackoverflow.com/questions/37635471/creating-a-hello-world-htmlwidget .  Do other known working`htmlwidgets` work for you?

**Comment by tbadams0405** [comment]
@timelyportfolio I talked with a friend of mine here and she pointed me in the right direction. Turns out that I just hadn't built/reloaded the package correctly. I had used devtools::reload but I don't think I ever built... I also didn't have Rtools installed, which didn't help either.

As for cross referencing, my bad! Will do in the future.

**Comment by timelyportfolio** [comment]
Glad you got it working.  Let me know if you run into any other problems.

**Comment by oganm** [comment]
I am wondering why `devtools::load_all()` isn't sufficient for this tutorial to work
