### ISSUE TITLE
pass x into widget_html

### ISSUE THREAD

**Issue by SymbolixAU** [ramnathv/htmlwidgets#212]
I've forked your repo and made a change to pass `x` into `widget_html()`
https://github.com/SymbolixAU/htmlwidgets/blob/master/R/htmlwidgets.R

This allows me to attach variables to `x` and pass them into `widget_html( )` to further customise said html. Is there a reason why this is not a valid approach? Or, would you like me to submit this as a pull request?

---

*References* 
Stack Overvlow question - http://stackoverflow.com/q/38297041/5977215

And the tweeted response by timelyportfolio: https://twitter.com/timelyportfolio/status/752313318610644992

**Comment by jjallaire** [comment]
The problem is that within Shiny applications "x" is not yet known at the
time widget_html is called.

The best way to accomplish this is to mutate the DOM as needed within the
first call to renderValue on the JavaScript side.

**Comment by SymbolixAU** [comment]
Ah I see; I hadn't got that far in my testing. 

Thanks for the comment - feel free to close this issue.

**Comment by SymbolixAU** [comment]
Do you have any hints on how to mutate the DOM within `renderValue` ?

I tried various attempts along the lines of

```
 renderValue: function(x) {
        //document.getElementById("my_script").innerHTML = "<p>test_html</P>";

        //$('#my_script').html('<p>test_html</p>');
 },
```

but I've never used javascript or htmlwidgets before so I can't get it to work

**Comment by ramnathv** [comment]
Here is a minimal example. The key concept to remember is that `el` refers to the DOM element into which the widget is rendered. So you can use `el` to do DOM mutations. In this example, we pass a `message` from R and render it as `paragraph`.

```js
HTMLWidgets.widget({
  name:  "foo",
  type: "output",
  factory: function(el, width, height) {
    // TODO: define shared variables for this instance
    return {
      renderValue: function(x) {
        // TODO: code to render the widget, e.g.
         el.innerHTML = "<p>" + x.message + "</p>"
      },
      resize: function(width, height) {
        // TODO: code to re-render the widget with a new size
      }
    };
  }
});
```

Hope this helps.

**Comment by SymbolixAU** [comment]
@ramnathv unfortunately I can't reproduce it. Here is an example on my github trying to use your code - https://github.com/SymbolixAU/myWidgetHTML

Nothing appears when I call `library(myWidgetHTML); myHTML(message = "hello world")` 

And inspecting the source doesn't show a any `<p>hellow world</p>` elements either

**Comment by timelyportfolio** [comment]
Is there a reason for your custom html script function?  This overrides the standard htmlwidget tags https://github.com/ramnathv/htmlwidgets/blob/master/R/htmlwidgets.R#L233, and in this case since you do not use htmlwidget id you lose reference to el.  See here for an example of custom html https://github.com/hrbrmstr/metricsgraphics/blob/master/R/metricsgraphics.R#L215 or for a little more complicated https://github.com/timelyportfolio/sunburstR/blob/master/R/sunburst.R#L111.

If you have not already, I would recommend learning chrome devtools https://developers.google.com/web/tools/chrome-devtools/?hl=en to help debug your widget.

**Comment by SymbolixAU** [comment]
Ahhh I see - it the custom `_html` was overriding the standard tags!

(FYI - I'm using a custom script function because (when I get my actual widget working) I need to load the js library dynamically for each user)

**Comment by ramnathv** [comment]
Can you not abstract the logic of the widget so that what you load per user is data and the script itself is just a function?

**Comment by SymbolixAU** [comment]
This seems like it should be a simple task.

The goal of my widget is to plot a google map. This HTML and js scripts generates a map on a web page, and is what I'm trying to turn into a widget in my googleway package: https://github.com/SymbolixAU/googleway/tree/map (on 'map' branch)

```
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet", type="text/css", href="resources/css/map.css">
    <script src="resources/js/initMap.js"></script>
    <script src="resources/js/loadMap.js"></script>
  </head>
  <body>
    <div id="map"></div>
    <script>
      initMap();
    </script>
    <script>
        window.onload = loadScript('a_valid_api_key');
    </script>
    <!-- standard api js call
    <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&callback=initMap"
    async defer></script>
    -->
  </body>
</html>
```

```
function initMap() {
        var mapDiv = document.getElementById('map');
        var map = new google.maps.Map(mapDiv, {
            center: {lat: 44.540, lng: -78.546},
            zoom: 8
        });
      }
```

```
//var GOOGLE_MAP_KEY = "a_valid_api_key";

function loadScript(GOOGLE_MAP_KEY) {
    var script = document.createElement('script');
    script.type = 'text/javascript';
    script.src = 'https://maps.googleapis.com/maps/api/js?' +
    'key=' + GOOGLE_MAP_KEY + '&callback=initMap';
    document.body.appendChild(script);
}
```

When I use the method suggested by ramnath I can inspect the source of the viewer and see the tags and scripts are there, but the map is not rendering

```
el.innerHTML = "<div id='map'></div><script>initMap();</script><script>window.onload = loadScript('" + x.key + "');</script>"
```

**Comment by ramnathv** [comment]
This might have something to do with the fact that it is an async call. The widgets rendered by `htmlwidgets` are rendered once the `DOMContentLoaded` event is fired by the page. I suspect that at this point, the scripts have not been loaded as yet, as a result of which the map is not rendered. @jcheng5 will be able to confirm this, and/or suggest alternate approaches.

**Comment by SymbolixAU** [comment]
If I move the api js call into the `<head>`, and remove the 'callback' argument I can get the html page to load

```
  <head>
    <style>
       #map {
        width: 100%;
        height: 400px;
      }
    </style>
      <script 
        src="https://maps.googleapis.com/maps/api/js?key=my_api_Key">
    </script>
  </head>
```

Is it possible to include html dependencies dynamically into the `widget_dependencies` function, and not just through the `dependencies.yaml`?

**Comment by timelyportfolio** [comment]
Yes you can provide dependencies outside of yaml through something like https://github.com/rstudio/leaflet/blob/master/R/plugin-providers.R#L38, but I don't think this will solve the problem.

**Comment by jcheng5** [comment]
@SymbolixAU Removing the `async defer` attributes from `<script>` and removing the callback argument, are indeed the correct steps IMHO.

Yes, you can include dependencies dynamically, as @timelyportfolio points out. I'd do that and also note that for your `htmlDependency` call, you can pass something like `script = c(href="https://maps.googleapis.com/maps/api/js?key=my_api_key")` to indicate that you're pointing to a hosted JS file. I *believe* this works with Rmd files (I mostly use this feature for Shiny).

**Comment by SymbolixAU** [comment]
The solution is so close...however, I'm failing to define `src` and `script` correctly in `htmlDependency`. I've tried various combinations of

```
google_key_dependency <- function(key) {

  list(
    htmltools::htmlDependency(
      name = "myName",
      version = "9999",
      src = c(href=paste0("https://maps.googleapis.com/maps/api/js?key=")),
      script = key))
      # src = c(href=paste0("https://maps.googleapis.com/maps/api/js?key=", key))
      # script = c(href=paste0("https://maps.googleapis.com/maps/api/js?key=", key))
    )
  )
}
```

The version shown here is generating a `<script src="https://maps.googleapis.com/maps/api/js?key=/xxxxxx"></script?>` element. However, when the page loads, it briefly shows a map, then throws an error for an invalid key due to the extra "/" at the front of the key. 

Do you have an example of a JS dependency that's completely hosted at a URL, rather than having JS code stored locally, that I could borrow?

(As an aside, it seems a hosted JS file the `name` and `version` arguments are arbitrary)

**Comment by jcheng5** [comment]
Hmm yeah it's a little weird. Set the src href to the URL up to the last /, and the script to everything after the last /.

**Comment by SymbolixAU** [comment]
The problem with that is the `?` and `=` get encoded to `%3F` and `%3D` respectively, which again gives an invalid `src=` argument

**Comment by jcheng5** [comment]
Shoot, that makes sense. How about something like src=".", head=tags$script(src="https://..."), all_files=FALSE?

**Comment by jcheng5** [comment]
(Sorry for the formatting, I'm on my phone)

**Comment by SymbolixAU** [comment]
I understand what you're suggesting with the `head` argument, and from `?htmltools::htmlDependency - head Arbitrary lines of HTML to insert into the document head` it appears the `head` argument should work. However, it's just inserting it as text into the `<body>`

```
<body ...>
  "script list(src = "https://maps.googleapi.com/...../js?key=xxxx") list() "
  <div ...
    <div ...
    </div>
  </div>
...
</body>
```

**Comment by SymbolixAU** [comment]
nevermind - I **think** I've got it working...

**Comment by SymbolixAU** [comment]
Thanks for all your help, @jjallaire , @jcheng5, @timelyportfolio  & @ramnathv, really appreciated.
