### ISSUE TITLE
Recommended way to use bootstrap and/or fontawesome console

### ISSUE THREAD

**Issue by daattali** [ramnathv/htmlwidgets#218]
Bootstrap and fontawesome are automatically loaded in shiny.  But if want to use any BS components or FA fonts in a widget, we need to remember that these libraries aren't available when rendering the widget in the RStudio console.  It's not a hard problem to solve, but I'm just wondering if there is any recommended/standard way to elegantly include these libraries from local disk only when needed

**Comment by jjallaire** [comment]
The rmarkdown package exports a bunch of dependencies (including bootstrap
and font awesome) which you can re-use in your widgets:

https://github.com/rstudio/rmarkdown/blob/master/R/html_dependencies.R

You can include these dependencies via the `dependencies` parameter of
`createWidget`:

https://github.com/ramnathv/htmlwidgets/blob/master/R/htmlwidgets.R#L308

Note though that bootstrap is typically provided by the page composition
environment (e.g. the html_document format). If you inject it into a random
page (e.g. a side deck or another page with it's own custom CSS) then
things might not turn out that well.

**Comment by daattali** [comment]
Thanks JJ, that was exactly what I needed -- a way to include bootstrap when needed but without having to include the logic myself.

I found a bug with loading font-awesome so I'll post a new issue and link here. Thanks!
