### ISSUE TITLE
About the necessity of `renderValue`. 

### ISSUE THREAD

**Issue by w9** [ramnathv/htmlwidgets#220]
Hi Ramnath, thanks for this wonderful package! :)

After looking at the documentation, I was wondering why the factory should include `renderValue` as part of the return value.

It seems to me that `renderValue`  is only going to be called once, which is exactly like the body of the `factory`. So wouldn't it make more sense to put the rendering steps directly in the body of the `factory`?

That is, instead of:

```
HTMLWidgets.widget({
  name: "...",
  type: "output",
  factory: function(el, width, height) {
    ... init steps ...
    return {
      renderValue: function(data) { ... render steps ... },
      resize: function(width, height) { ... },
    }; 
  }
});
```

how about just

```
HTMLWidgets.widget({
  name: "...",
  type: "output",
  factory: function(el, width, height, data) {
    ... init steps ...
    ... render steps ... 
    return {
      resize: function(width, height) { ... },
    }; 
  }
});
```

Is there a difference between the factory body and renderValue?

**Comment by jjallaire** [comment]
It's called once in R Markdown or any other static publishing environment
however it is called many times in a Shiny application as it reacts to
changes in inputs, etc.
