### ISSUE TITLE
Embeding Html extract into a different html doesn't work

### ISSUE THREAD

**Issue by kranthikandi** [ramnathv/htmlwidgets#222]
I have created a boxplot graph using plotly and did html extract using this
`htmlwidgets::saveWidget(as.widget(ggp), "working/directory/index.html")`.
this created a index.html and a directory called index_files.

Now I'm trying to embed this in `home.html` using `<div><embed src="index.html"></div>` it's showing a blank page.
It works only if redirect to a new page using `<a href="index.html">index</a>`.

**Comment by jcheng5** [comment]
The embed tag isn't for embedding HTML pages, but for plugins like Flash. Do you mean <iframe>?

**Comment by jcheng5** [comment]
(Sorry, comment got mangled)

Do you mean `<iframe>`?

**Comment by kranthikandi** [comment]
I have used `<iframe >` it works fine.
