### ISSUE TITLE
Make widgets communicate together

### ISSUE THREAD

**Issue by cuche27** [ramnathv/htmlwidgets#227]
It would be awesome if this package provided a simple and unified mechanism to let widgets communicate together so the final user has not to write some javascript code to manage interactions between widgets (At least the most simple ones).

### Use case
Imagine a shiny app with a world map and a time series chart containing one line per country. When the user hovers a country on the map, the javascript of the widget sends the id of the hovered polygon (for instance country name) to a global javascript object provided by `htmlwidgets`. Then this object sends this id to the other widgets of the page, here the time series chart which then highlights the series with the corresponding id. 

The only job for the user would be to pass to the two functions that generate the widgets the ids of the polygons and the time series and the link between widgets would be automatically created. It would be magical ! `(*o*)`

htmlwidget developers would have to actualize their javascript code to send messages to the object provided by htmlwidget and they would have to provide an additional function ("highlight" or something like this) that would be called when a message is sent by another widget.

**Comment by jjallaire** [comment]
Check out the crosstalk package: https://github.com/rstudio/crosstalk/blob/master/README.md

**Comment by timelyportfolio** [comment]
@cuche27 we are working on it.  For a very long discussion see #86.

**Comment by cuche27** [comment]
Ho ok. Sorry for duplication. I am eager to see the final result :)
