### ISSUE TITLE
dygraphs with huge file slow loading

### ISSUE THREAD

**Issue by victorjife** [ramnathv/htmlwidgets#233]
Hello, 
I'm doing a shiny app with dygraphs and my files are arround 500ks of rows. It is becameing very slow process because it load every point (more than one poin per pixel)
Is it any way for don't load the unnecessary points that it won't see?
I saw that are some way to do it for .html but i want to do it in .r

Thank you

**Comment by cpsievert** [comment]
This issue would be better filed here https://github.com/rstudio/dygraphs/issues/new
