### ISSUE TITLE
onRender example doesn't work in a shiny app

### ISSUE THREAD

**Issue by daattali** [ramnathv/htmlwidgets#236]
I've never used onRender() and I've never used leaflet until today, so it's very possible that I'm doing something wrong.  But it seems to me that since the `onRender()` example shows how to use it on a leaflet map, and leaflet maps can be inside shiny apps, then the same example should also work within a shiny app. Perhaps I'm wrong though?

This code is taken straight out of the documentation for `onRender` and it works:

```
meh <- "&#x1F610;";
yikes <- "&#x1F628;";

df <- data.frame(
  lng = quakes$long,
  lat = quakes$lat,
  html = ifelse(quakes$mag < 5.5, meh, yikes),
  stringsAsFactors = FALSE
)

leaflet() %>% addTiles() %>%
  fitBounds(min(df$lng), min(df$lat), max(df$lng), max(df$lat)) %>%
  onRender("
    function(el, x, data) {
      for (var i = 0; i < data.lng.length; i++) {
        var icon = L.divIcon({className: '', html: data.html[i]});
        L.marker([data.lat[i], data.lng[i]], {icon: icon}).addTo(this);
      }
    }
  ", data = df)
```

However, if I place it inside a shiny app, it doesn't work:

```
library(shiny)
library(leaflet)
library(htmlwidgets)

ui <- fluidPage(
  leafletOutput("mymap")
)

server <- function(input, output, session) {
  output$mymap <- renderLeaflet({
    meh <- "&#x1F610;";
    yikes <- "&#x1F628;";

    df <- data.frame(
      lng = quakes$long,
      lat = quakes$lat,
      html = ifelse(quakes$mag < 5.5, meh, yikes),
      stringsAsFactors = FALSE
    )

    leaflet() %>% addTiles() %>%
      fitBounds(min(df$lng), min(df$lat), max(df$lng), max(df$lat)) %>%
      onRender("
               function(el, x, data) {
               for (var i = 0; i < data.lng.length; i++) {
               var icon = L.divIcon({className: '', html: data.html[i]});
               L.marker([data.lat[i], data.lng[i]], {icon: icon}).addTo(this);
               }
               }
               ", data = df)
  })
}

shinyApp(ui, server)
```

Specifically, I see the following error in the javascript console:

```
leaflet.js:1516 Uncaught TypeError: Cannot read property 'getGroupNameFromLayerGroup' of undefined
```

The exact javascript code in that line is

```
map.layerManager.getGroupNameFromLayerGroup(e.layer)
```

So I then placed a simple `console.log(this.layerManager)` and I saw that indeed when running the map in the console it prints out a LayerManager object, but inside a shiny app it's undefined.

I'm not sure if this is a bug or expected, but to someone with no prior experience like myself it seems like unexpected behaviour

**Comment by jcheng5** [comment]
Is there a particular branch or fork of leaflet that you were using?

**Comment by daattali** [comment]
Just installed leaflet from CRAN this morning.  v1.0.1

**Comment by jcheng5** [comment]
Ok, thanks. I see the problem I think--we are running the onRender code at the wrong time in the Shiny case. I'll submit a PR on Monday.
