### ISSUE TITLE
export getDependency

### ISSUE THREAD

**Issue by fbreitwieser** [ramnathv/htmlwidgets#242]
getDependency is currently not exported, but needed when using some packages. Example with `sparkline`: https://bl.ocks.org/timelyportfolio/086fbb2f63805cdb39a859a9fc6f0be5

**Comment by ramnathv** [comment]
The reason it was not exported originally was to allow some flexibility in the underlying dependency fetching mechanism. Given that the current mechanism has been stable for a long time now, we can certainly think about exporting it. @jjallaire @jcheng5 @timelyportfolio @yihui any thoughts on this?

**Comment by timelyportfolio** [comment]
I use it very frequently, so I am a strong advocate for exporting.

**Comment by jjallaire** [comment]
I'd be fine with exporting it.

**Comment by ramnathv** [comment]
Done in b759e052ce3383946370f63e3ff41ce9d873b1cc.
