### ISSUE TITLE
Binary Data w/o base64 encoding

### ISSUE THREAD

**Issue by bhaskarvk** [ramnathv/htmlwidgets#246]
Any plans on supporting transferring binary data w/o the need to base64 encode it? 
I am thinking of using https://github.com/jeroenooms/protolite for leaflet to transfer huge geojson files, but the need to base64-ize and JSON-ize the resultant protobuf encoded data, makes the whole thing kind of pointless.

Ideal solution would be to load the serialized binary data over HTTP/s and not being embedded as a base64 encoded data in the data json.

**Comment by bhaskarvk** [comment]
cc @timelyportfolio @jcheng5

**Comment by jcheng5** [comment]
Unfortunately that would mean the resulting .html files couldn't be just opened in a web browser, but would have to be served from an actual web server. Also we'd need the ability to load the data synchronously I think. I'd love a solution to this but I don't have an idea right now that drops into the framework we have.

**Comment by bhaskarvk** [comment]
I would argue that the primary delivery mechanism of HTML files is a web server. Being able to open them as local files is an interesting side effect. Also you don't necessarily need to load the data synchronously. Here's how I'm doing asynchronous GeoJSON loading in leaflet.extras

```javascript
 if(LeafletWidget.utils.isURL(geojson)) {
    $.getJSON(geojson, function(geojsondata){
      addGeoJSONLayer(geojsondata)
    }
} else { // either JSON object or string
    addGeoJSONLayer(geojson)
}
```

**Comment by bhaskarvk** [comment]
Another note, on the browser side using https://github.com/github/fetch#browser-support + https://github.com/taylorhakes/promise-polyfill (for older browser) gives a very easy and efficient mechanism for loading data asynchronously. All that needs to be figured out it how to serve it from an R session.

Also to your point about not being able to open files locally, I might add that this could be an optional mechanism for data transfer which works only over HTTP/s and the user will be expected to know this when using such a mechanism.

**Comment by jcheng5** [comment]
Oh, OK. I was envisioning a more transparent mechanism than what you're suggesting.

Just so we're clear on what the limitations would be:

1. No viewing .html files locally
2. No `self_contained: true`
3. No publishing to RPubs (which needs `self_contained: true`)
4. Async loading of data

Can you achieve this today just by allowing relative URLs and putting the data file in the same directory as (or subdir of) the .Rmd/.html files?

**Comment by bhaskarvk** [comment]
Yes I can achieve that, but that needs an extra step of creating the data file. I'm trying to accomplish it using `httpuv` so that the contents can be dynamically generated. e.g instead of serving a GeoJSON, encode it using Geobuf in R and serve out the GeoBug encoded binary data over AJAX.

On an unrelated note, why does Rpubs need self_contained:true ? It should be possible to push a whole directory which has js libs/ data etc.

**Comment by jcheng5** [comment]
Then you already have what you need for that, don't you? Maybe I'm missing something.

RPubs could do that, it just doesn't. It expects each document to be a single self-contained .html file (or at least if it refers to resources, that those are on other hosts).
