### ISSUE TITLE
Confirm: "The rpivotTable package depends on the development version of the htmlwidgets package"?

### ISSUE THREAD

**Issue by GaryWMN** [ramnathv/htmlwidgets#247]
I do not understand why, but the [rpivotTable package](https://github.com/smartinsightsfromdata/rpivotTable) documentation states that it depends on the development version of the htmlwidgets package. Can anyone say if this is still the case? 

We are looking at upgrading our htmlwidgets package from 0.7 to 0.8. 

Also posted as [rpivotTable](https://github.com/smartinsightsfromdata/rpivotTable) [issue #61](https://github.com/smartinsightsfromdata/rpivotTable/issues/61)

**Comment by smartinsightsfromdata** [comment]
Replied here https://github.com/smartinsightsfromdata/rpivotTable/issues/61

**Comment by GaryWMN** [comment]
Excellent! We will proceed with our upgrades. Thanks for replying so timely!
