### ISSUE TITLE
Pandoc memory error

### ISSUE THREAD

**Issue by Nikolai-Hlubek** [ramnathv/htmlwidgets#248]
Hi guys

Ultimately I would like to see this issue fixed:
_https://github.com/ropensci/plotly/issues/822_
but the root cause is, that pandoc in htmlwidgets crashes because of an _out of memory_ error.
I do not even know if it is a real out of memory error or a recursion happening somewhere, because a 10MB functioning and complete html file is written and only after the file is written pandoc stalls and ultimately crashes.

**Comment by cpsievert** [comment]
To avoid this sort of problem you can set `selfcontained = FALSE` in `saveWidget()`
