### ISSUE TITLE
Embedding widgets in widgets

### ISSUE THREAD

**Issue by yonicd** [ramnathv/htmlwidgets#261]
I want to try and embed in an iframe src that will run an htmlwidget. And use that iframe in a div call in slickR ([which I did yesterday](https://twitter.com/yoniceedee/status/832306965204328448)) . This would allow to have many independent widgets (of say ggplotly) running at once. Is this possible? If so how would I go about it?

Thanks

**Comment by bhaskarvk** [comment]
Check my widgetframe package (available on CRAN) it does exactly this; wraps a widget in an iframe

**Comment by yonicd** [comment]
thanks! will do

**Comment by yonicd** [comment]
can frameWidget return src script and not open the viewer?

**Comment by yonicd** [comment]
i have a feeling that i would need to place `var pymParent = new pym.Parent('divId', x.url, {});` in the divs i create to place in the slick carousel.

how can i get the html from `widgetData`?

**Comment by bhaskarvk** [comment]
Could you open a issue on widgetframe with some sample code of what you are trying to do ? It is better for me to track this that way.

**Comment by yonicd** [comment]
thread continued [here](https://github.com/bhaskarvk/widgetframe/issues/4)

**Comment by timelyportfolio** [comment]
ok to close this one?
