### ISSUE TITLE
export JSEvals()?

### ISSUE THREAD

**Issue by Yang-Tang** [ramnathv/htmlwidgets#263]
Is it possible to export the `JSEvals()` function? I found it's quite useful to locate callback functions when handling some javascript libraries.

**Comment by ramnathv** [comment]
@yihui i remember there might have been some reasons behind not exporting `JSEvals`, or am i just imagining it :) ?

**Comment by yihui** [comment]
I have never felt I needed to use it from the perspective of either a user or a developer of a widget. Could you say more about its usefulness? i.e. why do you need to locate the JS expressions in a list?

**Comment by Yang-Tang** [comment]
@yihui I'm trying to write an R wrapper of a javascript library, but it's not a htmlwidget because it doesn't produce plots or visualizations. 
In order to pass callbacks as an option to a javascript function from R, I wrap js expressions with `htmlwidgets::JS()` in a list, add location index of them using `htmlwidgets:::JSEvals()` and send it to javascript by `session$sendCustomMessage`. In javascript side, I eval the expressions according to the location index similar to what `htmlwidget` does.
I think, by exporting `JSEvals()`, it would be more flexible for other javascript-based R packages to use it to handle js expressions.
I don't know whether this is an appropriate way to do it. I would be very appreciated if you could give some suggestions!

**Comment by yihui** [comment]
I see. Thanks for the explanation! That makes sense to me.

@ramnathv I'm okay with exporting this function. It is a little hackish (based on an undocumented behavior of `unlist()`), but I think it is fine.
