### ISSUE TITLE
How to use saveWidget to save a crosstalk result as local HTML file?

### ISSUE THREAD

**Issue by processadd** [ramnathv/htmlwidgets#266]
How to use htmlwidgets::saveWidget to save a crosstalk result like 
library(crosstalk)

shared_iris <- SharedData$new(iris)
hw <- bscols(
  d3scatter(shared_iris, ~Petal.Length, ~Petal.Width, ~Species, width="100%", height=300),
  d3scatter(shared_iris, ~Sepal.Length, ~Sepal.Width, ~Species, width="100%", height=300)
)

?? how to save hw as a local HTML file

Thanks!

**Comment by jjallaire** [comment]
The easiest thing might just be to place that code in an R Markdown document and render it.

That said, I know there is a way to do it from plain R but can't recall the specifics. @timelyportfolio ?

**Comment by jto888** [comment]
If you call for the widget in RStudio there is an Export option to "Save 
as webpage. . . "

**Comment by jjallaire** [comment]
Actually I think you can just do this:

```r
library(crosstalk)

shared_iris <- SharedData$new(iris)
hw <- bscols(
d3scatter(shared_iris, ~Petal.Length, ~Petal.Width, ~Species, width="100%", height=300),
d3scatter(shared_iris, ~Sepal.Length, ~Sepal.Width, ~Species, width="100%", height=300)
)
htmltools::save_html(hw)
```

**Comment by timelyportfolio** [comment]
If that does not work, see https://github.com/rstudio/htmltools/issues/73, and let me know.

**Comment by processadd** [comment]
Thanks everybody. save_html works. I tried like:
htmltools::save_html(hw, "foo.html", libdir = "lib"). It has some warnings:
Warning messages:
1: In format(object) : restarting interrupted promise evaluation
2: In get(method, envir = home) :
  restarting interrupted promise evaluation
3: In get(method, envir = home) : internal error -3 in R_decompress1
But I did see the html can be opened and showed correctly. 

hw$$children can return the divs but seems no way to get the dependency scripts.

**Comment by jcheng5** [comment]
The error will likely go away if you restart your R process. Every time I've seen that it's because devtools has tried and failed to completely unload an old version of a package.

**Comment by jcheng5** [comment]
And for the record, I agree with `htmltools::save_html()` being the answer for this; if it didn't work, I would consider it a bug.

**Comment by ismirsehregal** [comment]
Is there any way to programmatically save a **selfcontained** HTML file using `save_html`?

```
library(crosstalk)

shared_iris <- SharedData$new(iris)
hw <- bscols(
  d3scatter(shared_iris, ~Petal.Length, ~Petal.Width, ~Species, width="100%", height=300),
  d3scatter(shared_iris, ~Sepal.Length, ~Sepal.Width, ~Species, width="100%", height=300)
)
htmltools::save_html(hw, "result.html")
```

This by default creates a `lib` folder.

However, using **RStudio's export option** "Save as webpage. . . " a standalone HTML file is produced. - How is it done?

`htmlwidgets::saveWidget(hw, "result.html", selfcontained = TRUE)` results in 

> Error in .getNamespace(pkg) : 
>   invalid type/length (symbol/0) in vector allocation

which might be [expected](https://github.com/rstudio/htmltools/issues/73).

Any hints are very welcome! - Cheers

**Comment by danielludolf** [comment]
@ismirsehregal Did you ever figure out how RStudio's "Save as webpage" option creates a sole HTML file?
