### ISSUE TITLE
NULL values in shinyRenderWidget warn in R 3.4.0

### ISSUE THREAD

**Issue by jcheng5** [ramnathv/htmlwidgets#269]
If you use an htmlwidget render function with Shiny on R 3.4.0, you'll get a warning like this if the instance value is `NULL`:

```
Warning in structure(x, class = unique(c("AsIs", oldClass(x)))) :
  Calling 'structure(NULL, *)' is deprecated, as NULL cannot have attributes.
  Consider 'structure(list(), *)' instead.
```

This is originating in the `JSEvals` function, which calls `I(NULL)`. However a lot of the code before it also interacts with the instance value, fortunately it's mostly `$` calls which are safe to call on `NULL`. We might consider doing more-explicit handling of the `NULL` case further upstream and leave `JSEvals` the way it is (or do both).

Repro:

```r
library(shiny)
library(leaflet)

ui <- fluidPage(
  leafletOutput("map")
)

server <- function(input, output, session) {
  output$map <- renderLeaflet(NULL)
}

shinyApp(ui, server)
```

**Comment by Marco-Park90** [comment]
I have the same issue. I am reporting this very simple code as an example:

`library(shiny)

ui<-fluidPage(
  
  textInput("city", label = "Black/White", value = ""),
  leafletOutput("map")
)

  server <- function(input, output) {

  
  state <- reactiveValues()
  
  
  observe({
    state$x <- input$city
    state$y <- ifelse(state$x == "Yes", 
                      leaflet() %>% 
                        addProviderTiles(providers$OpenStreetMap.BlackAndWhite), 
                      leaflet() %>% 
                        addTiles()
                      )
  })
  

  
  
  output$map<-renderLeaflet({ state$y }) 


  
  
  
  
  }

shinyApp(ui = ui, server = server)


`

How can I fix it?

**Comment by jcheng5** [comment]
Installing the github version of the package should fix it--let us know if not!

**Comment by Marco-Park90** [comment]
Thanks, How do I install that version?

**Comment by jjallaire** [comment]
@jcheng5 Do we need a CRAN release of htmlwidgets? I noticed that there are 2 changes in there: this one and the one about dependency rendering order. On the second change I also noted there was some recent discussion about it having unexpected side effects (don't recall the details). Anyway, let me know if this should be going to CRAN soon.

**Comment by jcheng5** [comment]
@jjallaire Yeah, it would be good if we could go to CRAN. I don't think the second change made things worse--if you're talking about @cpsievert's recent issues and pull requests, they were all related to the order of dynamic dependencies vs. yaml dependencies, I believe. Whereas my change was related to the order of dynamic dependencies being loaded vs. the widget binding's init method being called.

**Comment by jjallaire** [comment]
Okay, update is on CRAN now.
