### ISSUE TITLE
No htmlwidget display in panel_div without some kind of initialzation

### ISSUE THREAD

**Issue by MikeWise2718** [ramnathv/htmlwidgets#276]
I noticed this as a result of this question: [visNetwork issue](https://stackoverflow.com/questions/44205545/visnetwork-not-displaying-in-panel-div/44211592#44211592). My first idea was that it was a `visNetwork` issue, but then I wondered if it is more an `htmlwidget` issue. So I tried with the `sigma` package and got the same result - so now I think it is an `htmlwidget` issue.

Here is the `sigma` example. This program displays fine:
```
library(shiny)
library(shinyLP)
library(sigma)

gexf <- system.file("examples/ediaspora.gexf.xml", package = "sigma")

ui <- fluidPage(
  sigmaOutput("network1",height=1,width=1), # empty network workaround
  panel_div("default", "panel1",sigmaOutput("network2")  )
)

server <- function(input, output) {
  
  output$network1 <- renderVisNetwork({ 
    # empty network
    nodes <- data.frame(id = NULL)
    edges <- data.frame(from =NULL, to = NULL)
    sigma(gexf,F,F)
  })
  
  output$network2 <- renderVisNetwork({ 
    # minimal network
    nodes <- data.frame(id = 1:3)
    edges <- data.frame(from = c(1,2), to = c(1,3))
    sigma(gexf,T,T)
  })
}
shinyApp(ui, server)
```

But if I comment out that first `sigmaOutput` in the `ui` portion, the `sigmaOutput` in the `panel_div` shows nothing. I know `panel_div` is not that commonly used for graphics, but it should work, right?

**Comment by jcheng5** [comment]
I'm not familiar with `panel_div`, is it this? https://github.com/jasdumas/shinyLP/blob/master/R/panel_div.R

If so, the issue is with the `panel_div` implementation. By coercing content to `character` (via `paste`) the htmltools dependency metadata is dropped--it's important not to do that. This is how it should be implemented (cc @jasdumas):

```r
panel_div <-function(class_type, panel_title, content) {
  div(class = sprintf("panel panel-%s", class_type),
    div(class = "panel-heading",
      h3(class = "panel-title", panel_title)
    ),
    div(class = "panel-body", content)
  )
}
```

**Comment by jasdumas** [comment]
^ I will implement those changes :)
