### ISSUE TITLE
htmlwidgets and deck.gl

### ISSUE THREAD

**Issue by alexonov** [ramnathv/htmlwidgets#291]
Hi, 
My question is wether htmlwidgets would be a suitable tool to create R bindings for deck.gl (https://uber.github.io/deck.gl/#/documentation/overview/introduction).

If so, could you point me in the main direction re the initial process, I would be happy to contribute.

Thanks in advance,

A

**Comment by cpsievert** [comment]
The reactR package should help you create an htmlwidget that uses this library 

https://cran.r-project.org/web/packages/reactR/vignettes/intro_htmlwidgets.html
https://github.com/react-R/reactR

**Comment by jcheng5** [comment]
There's this too https://github.com/SymbolixAU/mapdeck

**Comment by SymbolixAU** [comment]
As @jcheng5 points out, `mapdeck` is an htmlwidget binding to deck.gl. 

Suggest closing this issue?
