### ISSUE TITLE
Uncaught TypeError: instance.resize is not a function

### ISSUE THREAD

**Issue by Tixierae** [ramnathv/htmlwidgets#301]
Minimal reproducible example:

```
library(shiny)
library(C3) # install via devtools::install_github("tixierae/shinyJsTutorials/tutorials/materials2/C3")

server = function(input,output) {
    my_df = reactive({
        input$button
        my_df = list(a=runif(1,0,100),b=runif(1,0,100),c=runif(1,0,100))
        list(my_df=my_df)
    })
    output$my_pie1 = renderC3Pie({
        C3Pie(value = my_df()$my_df)
    })
}
ui = shinyUI(
    navbarPage(id="main", position = "fixed-top", title=NULL, inverse=T, selected="tab1",
        tabPanel("tab1",
            fluidRow(br(),br(),br(),
                actionButton("button", "Draw!"),
                C3PieOutput("my_pie1")
            )
        ),
        tabPanel("tab2",
            fluidRow(br(),br(),br(),
            )
        )
    )
)
shinyApp(ui=ui, server=server)
```
**Procedure to reproduce the error (happens at least on Chrome and Firefox)**: 
- go to 'tab2'
- generously zoom in or out
- go back to 'tab1'. The app is now frozen.

Inspect on Chrome shows:

```
Uncaught TypeError: instance.resize is not a function
    at Object.resize (htmlwidgets.js:822)
    at exports.OutputBinding.shinyBinding.resize (htmlwidgets.js:526)
    at output_binding_adapter.js:12
    at OutputBindingAdapter.onResize (utils.js:114)
    at HTMLDivElement.<anonymous> (init_shiny.js:305)
    at Function.each (jquery.min.js:2)
    at n.fn.init.each (jquery.min.js:2)
    at j (init_shiny.js:298)
    at Debouncer.$invoke (input_rate.js:56)
    at Debouncer.immediateCall (input_rate.js:44)
```

I'm working with the dev version of `htmlwidgets` (installed from GitHub).
`C3` is originally from the frissanalytics tutorials (https://shiny.rstudio.com/articles/js-widget-functionality.html). I just modified the colors of the pie chart.

**Comment by timelyportfolio** [comment]
Hi @Tixierae, I know it is hard to know sometimes where to post an issue, but please try not to crosspost and if you do, please list where all you have asked a question https://github.com/FrissAnalytics/shinyJsTutorials/issues/17.   This is not an `htmlwidgets` issue, so I will answer there.

**Comment by Tixierae** [comment]
Thanks for the quick reply. My apologies! I didn't know that crossposting was considered bad practice.

**Comment by timelyportfolio** [comment]
@Tixierae hard to keep up with all the rules of the internet :)  Hope the answer helps.

**Comment by Tixierae** [comment]
@timelyportfolio  Any chance you could look into this issue: https://github.com/FrissAnalytics/shinyJsTutorials/issues/18?
Your help would be much appreciated
