### ISSUE TITLE
Unable to install from github

### ISSUE THREAD

**Issue by irenebn** [ramnathv/htmlwidgets#311]
Dear all,

I get the following error when installing htmlwidgets from github:

> devtools::install_github('ramnathv/htmlwidgets')
Downloading GitHub repo ramnathv/htmlwidgets@master
from URL https://api.github.com/repos/ramnathv/htmlwidgets/zipball/master
Installation failed: 'exdir' does not exist

Any ideas?

**Comment by ramnathv** [comment]
@irenebn Any reasons not to install the package directly from CRAN?

**Comment by irenebn** [comment]
Thanks for your reply. It works now :)
