### ISSUE TITLE
my htmlwidgets work in shinyApp, not yet in RStudio - how to debug? sizing policy?

### ISSUE THREAD

**Issue by paul-shannon** [ramnathv/htmlwidgets#321]
I have two HTMLwidgets (cyjShiny, igvShiny) which work pretty well in shinyApps. My first attempt to use them for interactive display in a regular RStudio session failed: a canvas (panel) was created, but nothing displayed. I am not sure how to debug this.

Perhaps someone can point me to an HTMLWidgets demo or tutorial, one which produces an interactive widget which runs, displays and resizes properly in all three settings (a shinyApp, RStudio, a markdown document)?

Thanks!

**Comment by ramnathv** [comment]
@paul-shannon Can you provide any links to these widgets as well as code that would help us reproduce this issue?

**Comment by paul-shannon** [comment]
@ramnathv  Certainly, and thank you!  I fully expect that the problem lines in my coding .

 -   [cyjShiny](https://github.com/cytoscape/cyjShiny)
 -  [igvShiny](https://github.com/paul-shannon/igvShiny)

**Comment by ramnathv** [comment]
Thanks @paul-shannon! Can you also provide code that works for you in shiny, but does not render in RStudio?

**Comment by paul-shannon** [comment]
So grateful for your help @ramnathv !
The cytoscape.js htmlwidget (cyjShiny) is the best example:
  - [working shiny example](https://github.com/cytoscape/cyjShiny/tree/master/inst/examples/dataFrameGraphWithAnimation)
  - [broken RStudio example](https://github.com/cytoscape/cyjShiny/tree/master/inst/examples/rstudio/dataFrameDemo)

**Comment by paul-shannon** [comment]
@ramnathv Is there anything I can do to simplify matters, to make it easier to get your help?   Perhaps my examples can be improved?   Maybe, once I understand what I am now missing I could contribute an annotated tiny example to document those things, a tutorial which might be useful to future adopters?

(Once I get past my current confusion I am eager to use crosstalk in the htmlwidgets I develop for research in Alzheimer's Disease and pre-term birth.   I'll be grateful for your help in getting there!)

**Comment by ramnathv** [comment]
@paul-shannon I looked at your code and I think I know what the problems are:

1. Your bundle.js file refers to `Shiny` functions, which causes an error when it is not run as a shiny app. I would recommend using `HTMLWidgets.shinyMode` to check if it is running in shiny mode, and if it is True, then add shiny handlers.

2. You might need to add jquery and specify it as a dependency in the yaml file. Shiny loads jquery automatically, but for static HTML, you will need the dependency.

Hope this points you in the right direction.

**Comment by ramnathv** [comment]
@paul-shannon Yes. The two-way interactivity is only available inside a shiny app. When you render a widget to HTML outside of a shiny app, the interactivity is limited to the client-side (js) only. The `crosstalk` package allows widgets to communicate with each other outside of `shiny`, but the types  of interactivity provided are fairly limited.

**Comment by jcheng5** [comment]
I would just add that it's important to consult the JavaScript error console when debugging htmlwidgets. Neither the browser nor RStudio will go out of their way to inform you that a JavaScript error has occured, you really have to go look for yourself whether there is any error message and/or stack trace in the JS console.

**Comment by paul-shannon** [comment]
@jcheng5 - I agree.  Lots can be - and often is - revealed in the console.

@ramnathv Thanks for the clarification about the relative isolation, the lack of interactivity between R and javascript when using htmlwidgets with RStudio & markdown.

I doubt that this will be of  much interest, but just in case:   Bioconductor [RCyjs](https://bioconductor.org/packages/devel/bioc/html/RCyjs.html) and [igvR](https://bioconductor.org/packages/devel/bioc/html/igvR.html) packages offer the same js widgets used in igvShiny and cyjShiny.  They share an underlying websocket communication layer, provided by [BrowserViz](https://bioconductor.org/packages/devel/bioc/html/BrowserViz.html).  Both work well in RStudio and plain R.  We find them useful when back-and-forth communication between R and browser visualizations are needed.

I found that my widget resizing problems -- the height could never exceed the original height -- are explained and worked around with the [fillPage layout](https://shiny.rstudio.com/reference/shiny/0.14/fillPage.html) along with some custom css.

I think we can close this issue now.  Many thanks for your help working these things through!

**Comment by ramnathv** [comment]
@paul-shannon Thanks for the info. If a session running R on the server is available, then it opens up more possibilities. Shiny is probably the easiest way to build highly interactive apps. Using a websockets based approach with tools like `BrowserViz` is another. I would also recommend looking into `opencpu`, which is another framework that allows R functions to be called from web applications using a REST API. I will close this issue.
