### ISSUE TITLE
HTML padding

### ISSUE THREAD

**Issue by dipterix** [ramnathv/htmlwidgets#337]
Htmlwidget by default adds `40px` paddings to `<body>`. How hard will it be to add `padding:0;` as an option?

![image](https://user-images.githubusercontent.com/8163576/56484119-94be9980-6493-11e9-96df-5e604fe74eb7.png)

**Comment by jcheng5** [comment]
You can control the padding using the sizingPolicy parameter to createWidget; see ?sizingPolicy for more details.
