### ISSUE TITLE
Do I need to create the widget as a package?

### ISSUE THREAD

**Issue by abhsarma** [ramnathv/htmlwidgets#341]
I am trying to create a very basic widget. 
Am I missing something or it appears that I need to create a package to do that --- I can't just specify the path or use devtools::load_all(".") ?
Is there a way to just specify the path instead of installing it as a package everytime?

**Comment by timelyportfolio** [comment]
@abhsarma please see https://github.com/ramnathv/htmlwidgets/issues/305 and let us know if that addresses your problem.  Happy to help.

**Comment by abhsarma** [comment]
@timelyportfolio Thanks! I think that has all the information I need. I'll close the issue for now, but I really think that should be a part of the documentation.
