### ISSUE TITLE
htmlwidgets conflict with plotly on shiny

### ISSUE THREAD

**Issue by dingying85** [ramnathv/htmlwidgets#342]
Dear htmlwidges developer,

Recently I encounter an issue when I putting htmlwidgets on my R shiny server code (such as using networkD3 or others like collapsibleTree), my other interactive plots implemented with plotly stop loading and disappeared on the interface.

I am wondering whether anyone else encounter this issue. I really want to incorporate the nice htmlwidgets to shiny apps.

Thanks in advance.

**Comment by ramnathv** [comment]
@dingying85 It would be useful if you could provide a minimal reproducible example.

**Comment by dingying85** [comment]
Sure, please see the reproducible example as below:

Please see the example and please give some advice how to make it work, it
does not work on my end
library(shiny)
library(plotly)
library(networkD3)
library(treemap)
library(d3treeR)
ui <- fluidPage(
plotlyOutput("p"),
forceNetworkOutput("o"),
d3treeOutput("a")
)

server <- function(input, output, session) {

output$p <- renderPlotly({
ds <- data.frame(labels = c("A", "B", "C"), values = c(10, 40, 60))
plot_ly(ds, labels = ~labels, values = ~values) %>%
add_pie() %>%
layout(title = "Basic Pie Chart using Plotly")
})

output$o <- renderForceNetwork({
forceNetwork(Links = MisLinks, Nodes = MisNodes, Source = "source",
Target = "target", Value = "value", NodeID = "name",
Group = "group", opacity = 0.4, zoom = TRUE)

})

output$a <- renderD3tree({
data(GNI2014)

tm <-  treemap(
  GNI2014,
  index=c("continent", "iso3"),
  vSize="population",
  vColor="GNI",
  type="value"
)


d3tree( tm,rootname = "World" )

})

}

shinyApp(ui, server)

Ramnath Vaidyanathan <notifications@github.com> 于2019年7月11日周四 下午3:06写道：

**Comment by mdancho84** [comment]
I believe I have just encountered a similar issue, where migrating from `htmlwidgets 1.3` to `1.5` has caused my Plotly charts to stop displaying.

**Comment by jcheng5** [comment]
@mdancho84 Please see https://github.com/ramnathv/htmlwidgets/issues/349, sorry for the inconvenience.

**Comment by mdancho84** [comment]
No worries - I used `remotes::install_github("rstudio/shiny@rc-v1.4.0")` and I'm back up-and-running again. Thanks for all your efforts. Keep up the A.MAZ.ING work.

**Comment by cpsievert** [comment]
Please reopen if this still an issue
