### ISSUE TITLE
Troubles with the use of dygraphs

### ISSUE THREAD

**Issue by odelaigue** [ramnathv/htmlwidgets#356]
With htmlwidgets 1.5.1, there are some big troubles with some functions of the dygraphs package (e.g. dyStackedBarGroup or dyShadow).
Its is OK with the version 1.3.
I don't know if you should fix htmlwidgets or @pshevtsov should adapt dygraphs to version 1.5.1.

```
library(dygraphs)
library(magrittr)

## dataset
lungDeaths <- cbind(fdeaths, mdeaths, ldeaths, foo = fdeaths/2, bar = fdeaths/3)

## A bunch of different plotters together:
dygraph(lungDeaths) %>%
  dyRangeSelector() %>%
  dyBarSeries('bar') %>% 
  dyStemSeries('mdeaths') %>% 
  dyShadow('foo') %>% 
  dyFilledLine('fdeaths')

## Stacked Bar and Ribbon Graphs:  
dygraph(lungDeaths) %>% 
  dySeries('mdeaths', axis = 'y2') %>%
  dyAxis('y', valueRange = c(-100, 1000)) %>% 
  dyStackedBarGroup(c('ldeaths', 'fdeaths'))
```

**Comment by wch** [comment]
For the record, here's what I see when I run the first one:

![image](https://user-images.githubusercontent.com/86978/68416956-1b4e7600-015b-11ea-9d83-441bfeb076ba.png)

**Comment by wch** [comment]
I've bisected this to https://github.com/ramnathv/htmlwidgets/commit/c998faebcac70a5f442f21dc9d48562537ad1e5a

**Comment by cpsievert** [comment]
Here's a potential fix for this issue `remotes::install_github("ramnathv/htmlwidgets#177")`

**Comment by odelaigue** [comment]
Thank you very much for your responsiveness!

**Comment by odelaigue** [comment]
Do you think you will soon be submitting the latest version of htmlwidgets on the CRAN?
Currently, packages using dygraphs still present potential troubles with htmlwidgets version 1.5.1.

**Comment by timelyportfolio** [comment]
Thanks for all the work on this, but it seems https://github.com/rstudio/dygraphs/issues/237 is still not working even after the fix.  I'll dig a little when I have some time.
