### ISSUE TITLE
htmlwidgets::saveWidget selfContained adds <pre> tags around custom HTML

### ISSUE THREAD

**Issue by rfaelens** [ramnathv/htmlwidgets#358]
The `timevis` package uses the function `timevis_html` to add a custom zoom menu:
https://github.com/daattali/timevis/blob/be9756629bf12f5225d578d10c093d8f968f8551/R/timevis.R#L505

This works fine in combination with htmlwidgets::saveWidget selfContained=FALSE.
When using the selfContained=TRUE option however, the custom HTML is wrapped in `<pre>` tags, and is therefore not present in the output.

As a workaround, the generated HTML code can be adapted afterwards, but this is less than ideal.

Minimal reprex: https://gist.github.com/rfaelens/9dc31900c8e6601f2b978be4f5c4ec43
Referencing original issue: https://github.com/daattali/timevis/issues/87

**Comment by mstr3336** [comment]
I have a marginally related issue w/ `selfContained = TRUE` causing stylesheets to be mangled - 

When selfContained = TRUE, the following:

```r
attach_dependencies <- function(graph) {
  jquery <- htmltools::htmlDependency(
    "jquery", version = "3.4.1",
    src = list(href = "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/"),
    script = "jquery.min.js"
    )

  bootstrap <- htmltools::htmlDependency(
    "bootstrap",
    version = "3.4.1",
    src = list(href = "https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/css/"),
    stylesheet = "bootstrap.min.css"
  )

  graph$dependencies %<>% c(list(jquery, bootstrap))
  graph
}

graph %<>% attach_dependencies()

graph %>% htmlwidgets::saveWidget("my_widget.html", selfcontained = T)
```
Renders out as:

```html
<head>
<meta charset="utf-8">
<title>visNetwork</title>
<style>body{background-color:white;}</style>
<!--  minfied htmlwidgets src --><script></script>
<!-- minified vis-420.1/vis.css --><style type="text/css"></style>
<!-- minified vis.js --><script></script>
<!-- minified visnetwork bindings --><script></script>
<!-- minified jquery src --><script></script>
<!-- HERE IS THE PROBLEM -->
<!-- minified bootstrap css -->
<style type="text/css; charset=utf-8">
</style>
<!-- Above "type" is appended with "charset=utf-8" -->
<style type="text/css">div.vis-tooltip {display : none}</style>
</head>
```

### selfcontained = false

```html
<head>
<meta charset="utf-8">
<style>body{background-color:white;}</style>
<script src="workflow_graph_zoomed_files/htmlwidgets-1.3/htmlwidgets.js"></script>
<link href="workflow_graph_zoomed_files/vis-4.20.1/vis.css" rel="stylesheet">
<script src="workflow_graph_zoomed_files/vis-4.20.1/vis.min.js"></script>
<script src="workflow_graph_zoomed_files/visNetwork-binding-2.0.9/visNetwork.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css" rel="stylesheet">
  <title>visNetwork</title>
<style type="text/css">div.vis-tooltip {display : none}</style>
</head>
```

For whatever reason, in the case of the bootstrap stylesheet, when trying to embed it, `htmlwidgets` adds an extra qualifier to its `type` attribute, extending it from `type="text/css"` to `type="text/css; charset=utf-8"`.

As a result of this, the bootstrap stylesheet doesn't appear to be applied to my document. The only thing that seems to fix this client-side (via devtools / browser inspect) is to modify the `type` attribute of this `<style>` tag, changing it from:

```html
<style type="text/css; charset=utf-8">...</style>
```

 back to:

```html
<style type="text/css">...</style>
```

In order to fix this mangling, I can probably run some clientside jquery that just finds instances of this value for type and restores them, but this fix isn't exactly cute.

**Comment by mstr3336** [comment]
The following serves as an effective workaround:

```js
// inst/lib/fix_utf.js
$(function() {
  $('style[type="text/css; charset=utf-8"]').attr("type", "text/css");
})
```

```r
attach_dependencies <- function(graph) {
  jquery <- htmltools::htmlDependency(
    "jquery", version = "3.4.1",
    src = list(href = "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/"),
    script = "jquery.min.js"
    )

  bootstrap <- htmltools::htmlDependency(
    "bootstrap",
    version = "3.4.1",
    src = list(href = "https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/css/"),
    stylesheet = "bootstrap.min.css"
    )

    fix_utf <- htmltools::htmlDependency(
      "fix_utf",
      "0.0.0.9001",
      package = "mandrake",
      src = "lib",
      script = "fix_utf.js"
   )
  graph$dependencies %<>% c(list(jquery, bootstrap,  fix_utf))
  graph
}

graph %<>% attach_dependencies()

graph %>% htmlwidgets::saveWidget("my_widget.html", selfcontained = T)

```

**Comment by ismirsehregal** [comment]
I'm having the same issue.

**Comment by jcheng5** [comment]
I'm not seeing it, it might be down to your Pandoc version. What does `rmarkdown::pandoc_version()` report? And what version of RStudio?

**Comment by ismirsehregal** [comment]
@jcheng5 thanks for the response!

I'm using RStudio version 1.4.869 and pandoc version 2.10.1

@rfaelens [reprex](https://gist.github.com/rfaelens/9dc31900c8e6601f2b978be4f5c4ec43) renders:

for `selfcontained = TRUE`
![image](https://user-images.githubusercontent.com/36849480/98787246-8af6e100-23ff-11eb-9344-6d6e57d6234d.png)

for `selfcontained = FALSE` (you can see the buttons in the upper right corner)
![image](https://user-images.githubusercontent.com/36849480/98787321-a7931900-23ff-11eb-8b46-d268125edab9.png)

**Comment by ismirsehregal** [comment]
@jcheng5 were you able to reproduce this with the above mentioned versions?

**Comment by ismirsehregal** [comment]
@andrewdenner I just rendered @rfaelens [reprex](https://gist.github.com/rfaelens/9dc31900c8e6601f2b978be4f5c4ec43) using your PR. Unfortunately the result remains the same on my machine.
