### ISSUE TITLE
knitr options saveWidget 

### ISSUE THREAD

**Issue by jennylsmith** [ramnathv/htmlwidgets#363]
Hello, 

I am trying to create a larger and higher resolution html file for a plot.ly R 3D scatter plot. I created the plot, and I am saving it as follows:
```
htmlwidgets::saveWidget(as_widget(plotly_3Dscatter),"output.html", background = bgcol, knitrOptions = list(dpi=1200,  fig.height = 15, fig.width=15, out.width=15,  out.height=15))
```

However, changing the dpi, height, and width options to any value - even what seems to be unreasonably large, doesn't appear to change the actual HTML output in any way.  I could not find a an example for the `knitrOptions`, so I am thinking my syntax may not be correct?

Thanks,

Jenny

**Comment by ramnathv** [comment]
@jennylsmith The `knitr` options you have specified only affect static plots. You can directly set the width and height of the plot in your call to `plotly`. Almost all `htmlwidgets`  allow setting these dimensions. Additionally, I believe, you can use `output.width` and `output.height` to control dimensions from `knitr`.

**Comment by jennylsmith** [comment]
Ok thanks!
