### ISSUE TITLE
savewidget error in Docker

### ISSUE THREAD

**Issue by silverstone1903** [ramnathv/htmlwidgets#364]
Hi,

First of all I'm not sure about this error is related with htmlwidgets but wanted to open an issue in here. I'm trying to Dockerize an application. I'm using `Rscript` command with script which is doing aggregation etc. to create a html table via DT package. 

`saveWidget(dt, 'dt.html', selfcontained = T)`

I'm getting an error when I want to save a DT object. 

`Error in system.file(config, package = package) : 
  'package' must be of length 1
Calls: saveWidget ... getDependency -> <Anonymous> -> inherits -> system.file
Execution halted
` 

ps:  BTW it gives that error in Docker with Ubuntu (latest) image.

**Comment by ramnathv** [comment]
@silverstone1903 Can you provide some more details on the actual docker image you are using. Also, can you tell us if setting `selfcontained = FALSE` works? If that does, then it is most likely that you don't have `pandoc` installed in your docker container, since it is used behind the scenes to make html self contained.

**Comment by silverstone1903** [comment]
Thank you for your answer. Sure @ramnathv, here is the Dockerfile. I added pandoc to the list but now it gives a different error which is in the below.

```
# Dockerfile
FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends build-essential r-base  python3.6 python3-pip python3-setuptools python3-dev nano r-cran-data.table r-base-dev libcurl4-openssl-dev libssl-dev libxml2-dev r-cran-rcpp r-cran-curl r-cran-openssl r-cran-xml2 python-wget r-cran-dt r-cran-htmlwidgets pandoc

COPY . /app
WORKDIR /app
RUN pip3 install -r requirements.txt # install python packages
RUN python3 /app/my_script.py # run python script

RUN Rscript /app/rpackages.R # install additional r packages
RUN Rscript /app/my_script.R # run r script


ENTRYPOINT [ "python3" ] 
CMD [ "app.py" ]

```

It gives an error when `selfcontained = T` or `selfcontained = F`.
```
Error in if (isdir && !dir_exists(to)) dir.create(to) :
  missing value where TRUE/FALSE needed
Calls: saveWidget ... lapply -> FUN -> <Anonymous> -> mapply -> <Anonymous>
Execution halted
```

**Comment by ramnathv** [comment]
The error seems to be because of a bug in how DT was built on Debian. See this issue for reference https://github.com/r-lib/covr/issues/328. Also, the binary used is DT 0.4, which is a really old version of `DT`. Installing the latest versions of the packages from CRAN solved the problem for me.

**Comment by silverstone1903** [comment]
I didn't notice that I'm using the old version of DT. I changed the Dockerfile due to your warning and now it works. Thank you so much for your help! @ramnathv
