### ISSUE TITLE
How to render an htmlwidget into a shiny application?

### ISSUE THREAD

**Issue by lc5415** [ramnathv/htmlwidgets#365]
Hello,

I have tried using [htmlwidgets-shiny](https://www.rdocumentation.org/packages/htmlwidgets/versions/1.5.1/topics/htmlwidgets-shiny) but I find the documentation hard to understand. The documentation would benefit from a clearer example and ideally, I would like to give the directory of my HTML widget and have the file rendered into a shiny application.

As an example, I would like to be able do something like:
```
p1 = economics %>% plot_ly(x = ~pop, y = ~unemploy, type = "scatter", mode = "markers")
p2 = economics %>% plot_ly(x = ~pop, y = ~pce, type = "scatter", mode = "markers")
saveWidget(p1, "p1.html")
saveWidget(p2, "p2.html")

selectInput("option", label = "Option",
              choices = c("1" , "2"), selected = "1")

render( # whichever render function could work
      switch(input$option,
           "1" = "p1.html",
           "2" = "p2.html"
)
```

How could I achieve this with the current htmlwidgets functions?

**Comment by jcheng5** [comment]
Each htmlwidget (such as plotly) should include their own output/render functions; as the user of such a widget, you should only need to use those. They generally want a render expression to yield the htmlwidget object in question, not an HTML file.

In your UI:

```r
plotlyOutput("myplot")
```

_Above_ your server function:
```r
p1 <- economics %>% plot_ly(x = ~pop, y = ~unemploy, type = "scatter", mode = "markers")
p2 <- economics %>% plot_ly(x = ~pop, y = ~pce, type = "scatter", mode = "markers")
```

_Inside_ your server function:

```r
output$myplot <- renderPlotly({
  switch(input$option,
    "1" = p1,
    "2" = p2)
})
```
