### ISSUE TITLE
selfcontained = FALSE

### ISSUE THREAD

**Issue by under-score** [ramnathv/htmlwidgets#366]
I have been referred here from a [mapview question](https://github.com/r-spatial/mapview/issues/286#issuecomment-622325095). Is there any chance to have ALL JS code outsourced to extra files to squeeze them using minify? My maps are way too large right now.

**Comment by jcheng5** [comment]
Those really have to be inline, they're not JS code at all but just JSON data. But maybe this would help? https://www.npmjs.com/package/gulp-minify-inline

If you are dealing with shape data you might also try simplification if you haven't already...?

**Comment by under-score** [comment]
thank so much, haven't really looked into the details of that 20 MB file that is being produced riht now (and not up to date to current web standards). [Can the data be compressed?](https://coderwall.com/p/mekopw/jsonc-compress-your-json-data-up-to-80)
Will explore also possibilities to reduce my shape data...

**Comment by under-score** [comment]
I think data reduction did the trick. Can recommend
`rmapshaper::ms_simplify(data, keep = 0.05, keep_shapes = TRUE)`
