### ISSUE TITLE
RStudio not loading data files that JS requests

### ISSUE THREAD

**Issue by andyreagan** [ramnathv/htmlwidgets#367]
The `altair` data visualization package relies on `vegawidget`, which wraps this package, `htmlwidgets`. This all sits on top of a JS visualization tool, "vega-lite". The tool relies on a JSON chart specification, and the data to be visualized in that JSON spec. Optionally, for vega-lite, you can pass a link to a JSON file that it will load for the data. This is very important because sometimes the data is very big and directly serializing the data into the HTML (as JSON) is inefficient, so we'd rather have JS load the JSON file of the data itself (which the the vega-lite embed library supports).

TLDR: The plots in RStudio that rely on loading a JSON file from the local filesystem don't work, but if I save the HTML to a file, run a local webserver (outside of RStudio) and use a browser to load this file, the plot works because it's able to load the JSON data file (the browser needs the webserver to do this).

Here's an example of a plot that will not work in RStudio:

```
library(altair)
alt$data_transformers$enable('json')

vega_data <- import_vega_data()

chart <- 
  alt$Chart(vega_data$cars())$
  mark_point()$
  encode(
    x = "Horsepower:Q",
    y = "Miles_per_Gallon:Q",
    color = "Origin:N"
  )

chart
```

**Comment by jcheng5** [comment]
Any chance this only happens on R 4.0.0, and only on Windows? https://github.com/rstudio/rstudio/issues/6737

**Comment by andyreagan** [comment]
I'm on OSX so it's not that...

**Comment by andyreagan** [comment]
I'll grab my version of R and the relevant libraries and post those with
the example.

**Comment by jcheng5** [comment]
Oh, forget what I said. I see now what you mean.

I had written up a detailed response talking about the "attachment" feature of htmltools/htmlwidgets, but, it looks like vegawidgets already uses it. The `vegawidgets::vegawidgets()` function has a `base_url` parameter, if altair passes `"."` to it then everything seems to work fine. (I can't speak to whether passing `base_url` has any downsides.)

**Comment by andyreagan** [comment]
Oh so it's not that RStudio can't pick up local files at all, it's getting
the URL right.

I'll see if I can reproduce that, and then close this issue to take it up
with `altair`.
--
Andy Reagan, PhD
andyreagan.github.io
@andyreagan <http://twitter.com/andyreagan>

Senior Data Scientist
MassMutual
datascience.massmutual.com

Founder
Quokka Labs Inc
quokkalabs.io
