### ISSUE TITLE
Can't find function

### ISSUE THREAD

**Issue by bhaveshnarra** [ramnathv/htmlwidgets#369]
Hi, I'm just a newbie htmlwidgets user. I followed the documentation on https://www.htmlwidgets.org/develop_intro.html
I encounter can't find function error after calling scaffoldWidget('X',edit=FALSE), install(),library('X')
X('Hello, World!'). The NAMESPACE file is empty as well.

Using R 4.0.0 and ubuntu 20.04
![Screenshot from 2020-05-23 22-40-41](https://user-images.githubusercontent.com/52484030/82736434-63279a00-9d47-11ea-8f5c-b8c0381d7623.png)

**Comment by jcheng5** [comment]
Hmmm, it works for me. Is there anything in `~/programming/R_projects/LACEview/R/LACEview.R?`

**Comment by bhaveshnarra** [comment]
Nothing more than the boiler plate code

**Comment by jcheng5** [comment]
Oh, but the boilerplate code is there? That's good. Does your NAMESPACE file not even include this?

```
# Generated by roxygen2: fake comment so roxygen2 overwrites silently.
exportPattern("^[^\\.]")
```

**Comment by bhaveshnarra** [comment]
it doesnt. it has
'''
# Generated by roxygen2: do not edit by hand
'''

**Comment by jcheng5** [comment]
Weird, no idea why. Well add that missing line to NAMESPACE, and try `install()` again, it should work.

**Comment by bhaveshnarra** [comment]
@jcheng5 it works thanks. But what could be the cause of this error?

**Comment by jcheng5** [comment]
@bhaveshnarra What does `packageVersion("usethis")` give you?

**Comment by bhaveshnarra** [comment]
1.6.1

**Comment by jcheng5** [comment]
I can reproduce this with R 4.0.0--the namespace is empty.

So the missing part is that after `scaffoldWidget()` but before `install()`, a call to `document()` is necessary so that the NAMESPACE can be regenerated by roxygen. I'll file a PR for a doc change.

Thank you for the report!
