### ISSUE TITLE
*_html protection?

### ISSUE THREAD

**Issue by thebioengineer** [ramnathv/htmlwidgets#376]
Working on developing an html widget and I accidentally started implementing the "*_html" method for creating custom "housings" for widgets.

I was very surprised and thought it was a bug until I found [your documentation](http://www.htmlwidgets.org/develop_advanced.html#custom-html-widget). 

Would it maybe be good to add protections around the calling of the function and ensuring that it returns a valid shiny.tag class and throw a warning? 

For backwards compatibility it might be a nightmare, but could there be a case for converting widget_html into a method/switch where it looks for widget_html.widgetname? that seems like it would be more in-line with standard R practice for different behavior for your custom classes.

```r
widget_html <- function (name, package, id, style, class, inline = FALSE, ...) {
    fn <- tryCatch(get(paste0("widget_html.",name), asNamespace(package), 
        inherits = FALSE), error = function(e) widget_html.default)
    fn(id = id, style = style, class = class, ...)
}

widget_html.default <- function (name, package, id, style, class, inline = FALSE, ...) {
   if (inline) {
        tags$span(id = id, style = style, class = class)
    } else {
        tags$div(id = id, style = style, class = class)
    }
}
```

**Comment by jcheng5** [comment]
Thanks, Ellis--both sound like good suggestions to me. Any chance you're up for preparing a PR?

**Comment by thebioengineer** [comment]
Sure thing @jcheng5 - is there one you prefer? (both could be implemented as well)

**Comment by jcheng5** [comment]
I think they're complementary? The warning to catch if you've stumbled into this accidentally like you did. The S3 method to make it possible to eventually deprecate the old way.

**Comment by thebioengineer** [comment]
Perfect. I'll aim to open a PR tomorrow. Thanks Joe!

**Comment by cpsievert** [comment]
I think this has been addressed by https://github.com/ramnathv/htmlwidgets/pull/378?
