### ISSUE TITLE
use of lapply

### ISSUE THREAD

**Issue by femiguez** [ramnathv/htmlwidgets#380]
I reported this issue here: https://github.com/timelyportfolio/listviewer/issues/35#issue-680518080
but it was suggested it belongs in this package. Thanks!

**Comment by jcheng5** [comment]
I'm not totally sure this is a bug at all. That structure looks like this:

```r
list(meta = list(), meta = list(), meta = list(), title = list(
    "R: The R Project for Statistical Computing"), link = list(), 
    link = list(), "[ comment ]", link = list(), link = list(), 
    "[ comment ]", "[ comment ]", "[ comment ]")
```

Some list items are named, some are not; and the names `meta` and `link` are used multiple times. Neither of these are legal in JSON, and indeed if you call toJSON on it you get something that is legal but doesn't make a ton of sense:

```json
{
  "meta": [],
  "meta.1": [],
  "meta.2": [],
  "title": [
    "R: The R Project for Statistical Computing"
  ],
  "link": [],
  "link.1": [],
  "7": "[ comment ]",
  "link.2": [],
  "link.3": [],
  "10": "[ comment ]",
  "11": "[ comment ]",
  "12": "[ comment ]"
}
```

While the error message is a bit surprising, I don't think it's asking too much to expect that the object being passed to `htmlwidgets::createWidget()` should be shaped like something that can sensibly be turned into JSON. But you and @timelyportfolio definitely let me know if you disagree.

**Comment by timelyportfolio** [comment]
I don't have a strong opinion and agree that this is definitely an edge case that might not need to be resolved in `htmlwidgets`.  In general most `htmlwidgets` expect a `data.frame`-like structure that will not present this problem.  The `list(1, x=2)` case is potentially more likely to be faced, but even then I think is improbable.

**Comment by femiguez** [comment]
Thanks for the feedback! It helps me understand this better and I can easily work around the issue. The actual case where I encountered this error was different from the one I posted. I presented it as an easily to reproducible example. It's just that the error message was a bit puzzling. I don't have concerns if you want to close this.
