### ISSUE TITLE
Unused Argument (reportTheme=TRUE) with PlotlyOutput

### ISSUE THREAD

**Issue by apalacio9502** [ramnathv/htmlwidgets#390]
I updated htmlwidgets to the last version in CRAN and I got the next error when I run my shiny app:

`` ''
Error in (function (outputId, name, width, height, package = name, inline = FALSE,:
  unused argument (reportTheme = TRUE)
`` ''

I traced the error and I found that the issue has relation with plotly:

```
2. 3.
do.call (htmlwidgets :: shinyWidgetOutput, args)
22.
plotlyOutput ("MOD_GE_SUB_ADM_C1_plot_1")
```

I have the last version of plotly (4.92), shiny (1.5) and htmwidgets (1.5.2) avalible in CRAN. My R version is 4.0.2.

**Comment by ismirsehregal** [comment]
Please see this: https://github.com/ropensci/plotly/issues/1868

**Comment by apalacio9502** [comment]
Thank you!
