### ISSUE TITLE
Apparent bug - operator precedence 

### ISSUE THREAD

**Issue by oliverbock** [ramnathv/htmlwidgets#408]
At https://github.com/ramnathv/htmlwidgets/blob/31dd9451f454de75dac78dd9f2d1bd9e87c27a60/inst/www/htmlwidgets.js#L254, the condition

    `if (!error instanceof SyntaxError) {`

will never succeed because `!` takes precedence over `instanceof`.

**Comment by wch** [comment]
Thanks for the report. Just curious: Did you run into this issue in practice, or did you happen to see it when looking at the code?
