### ISSUE TITLE
PANDOC.md no longer exists

### ISSUE THREAD

**Issue by dmurdoch** [ramnathv/htmlwidgets#416]
If Pandoc is not found, `savewidget()` will print a message:

https://github.com/ramnathv/htmlwidgets/blob/31dd9451f454de75dac78dd9f2d1bd9e87c27a60/R/savewidget.R#L46-L47

However, the cited file was moved to `vignettes/pandoc.Rmd` in June 2019 (https://github.com/rstudio/rmarkdown/commit/45d6c817404949e466cbe856f6527236c891c77c), and deleted in Sept 2020 (https://github.com/rstudio/rmarkdown/commit/ef67a830efb225d2d0a9f4c06a8701bab126e289). 

I don't know a suitable reference to use instead, so maybe the "For details" part should just be removed?

**Comment by cpsievert** [comment]
This should be fixed by #443
