### ISSUE TITLE
Rules issue

### ISSUE THREAD

**Issue by letasos** [ramnathv/htmlwidgets#424]
Hello everyone,

The last few days i keep facing the same issue with the output. I have tried everything like delete R, install again the libraries & .etc but the issue is still there.

As you can see from the attached file im not able to see the rules or any information on the output.

If anyone knows what is wrong please let me know.

Thanks 
![rules issue](https://user-images.githubusercontent.com/76747836/147144207-b3ff78e8-54e9-4404-a1ca-bddbe05f5b7e.PNG)

**Comment by jcheng5** [comment]
Hello! Please file this issue on the GitHub repo of the actual package you're using to generate the visualization. This repo is for the htmlwidgets package, which is an underlying component of many visualization packages, but does not itself generate any visuals.

**Comment by letasos** [comment]
Hello Joe and thanks for your quick response.

The line of code that im using for this plot is plot(rules, method = "graph",  engine = "htmlwidget").

My apologies if im still off threat 

@jcheng5

**Comment by jcheng5** [comment]
I'm guessing you're using arulesViz to create the `rules` object? If so, then this bug might already be fixed: https://github.com/mhahsler/arulesViz/issues/21

**Comment by letasos** [comment]
Thanks Joe you are right! thanks for you help and happy holidays!
