### ISSUE TITLE
R <-> htmlwidget interactivity? (i.e. setZoom(2) AND getZoom())

### ISSUE THREAD

**Issue by paul-shannon** [ramnathv/htmlwidgets#431]
Can an htmlwidget, once created, keep its websocket connection open,  between R and the browser, so that further commands can be issued, and responses returned?  
For example, imagine an htmlwidget that displays an image, and then supports interactive control and querying  *from R*:  
```
R> w <- imageDisplayWidget("something.jpg")
R> getZoom(w)   # would return 1.0
R> setZoom(w, 3)
R> getZoom(w)   # would return 3.0
```
Thank you.

**Comment by cpsievert** [comment]
It's possible to achieve something like this with Shiny and the concept of a "proxy" object. See, for example, `leaflet::leafletProxy()` or `DT::dataTableProxy()`.

Closing since, if there is anything we can do here to make this easier, the htmlwidgets package isn't the place to do so.
