### ISSUE TITLE
Feature request: `onRender` for 3D plots in `plotly`

### ISSUE THREAD

**Issue by rasenior** [ramnathv/htmlwidgets#432]
The `onrender` function is perfect for adding a hyperlink to points in a plotly graph, as in the example below:

```
library(htmlwidgets)

p <- plot_ly(mtcars, x = ~wt, y = ~mpg) %>%
  add_markers(
    text = rownames(mtcars),
    customdata = paste0("http://google.com/#q=", rownames(mtcars))
  )
  
onRender(
  p, "
  function(el) {
    el.on('plotly_click', function(d) {
      var url = d.points[0].customdata;
      window.open(url);
    });
  }
")
```

However, as noted in Chapter 21 of [“Interactive web-based data visualization with R, plotly, and shiny”](https://plotly-r.com/supplying-custom-data.html#fig:tooltip-image), this doesn't currently work for 3D plots. I can only present my data in 3D because it's Red, Green, Blue colour data, so it would be really great if a workaround could be found for 3D plots.

**Comment by cpsievert** [comment]
This is a limitation of plotly.js, please file an issue there https://github.com/plotly/plotly.js/issues
