### ISSUE TITLE
saveWidget warning from pandoc

### ISSUE THREAD

**Issue by neuwirthe** [ramnathv/htmlwidgets#433]
Error message from saveWidget:
`[WARNING] Deprecated: --self-contained. use --embed-resources --standalone`

The latest version of pandoc 2.19 seems do deprecate option `--self-contained`

It is called in `htmlwidgets:::pandoc_self_contained_html` in the lines 
 
```   
pandoc_convert(input = input, from = "markdown", output = output, 
options = c("--self-contained", "--template", template))
```

so perhaps this needs to be adapted.

**Comment by neuwirthe** [comment]
I created a branch taking care of the problem and submitted a pull request. The modified version is in the repo `neuwirthe/htmlwidgets`

**Comment by c-brendel** [comment]
I also noticed this. Would be nice if they could merge your pull request!
