### ISSUE TITLE
Feature request: get widget html

### ISSUE THREAD

**Issue by ArthurAndrews** [ramnathv/htmlwidgets#436]
Thanks for the great package!

I've had to work a few times with the widget html.  This is required, for example, for displaying widgets on Databricks.
https://docs.databricks.com/notebooks/visualizations/htmlwidgets.html

The current solutions are kind of kludgey - require writing to a temp file with `saveWidget` and reading the contents of the temp file.  It would be nice to have a function to get the html directly.  Thanks!

**Comment by cpsievert** [comment]
Can you call `htmltools::as.tags()` on the widget instance?
