### ISSUE TITLE
¶ character appearing in html in output of saveWidget

### ISSUE THREAD

**Issue by anoronh4** [ramnathv/htmlwidgets#448]
i am using the function `htmlwidgets::saveWidget(plot, paste0(opt$sampleName,".circos.html"), selfcontained = T, libdir = "lib")` and finding an odd artifact, basically the ¶ character appearing 4 times in the top left corner. i see this in two different browsers (chrome and firefox). i have attached the file in this post. A workaround at the moment is to do a replacement on the file using: `sed "s/¶/<p><\/p>/g"` but i'm wondering if this is maybe a bug or if there's something i can do within R. I am using htmlwidgets_1.5.4 and R version 4.2.2. 
[circos.zip](https://github.com/ramnathv/htmlwidgets/files/10106838/circos.zip)

**Comment by cpsievert** [comment]
Please provide a fully reproducible code example (i.e., code to reproduce `plot`) as well as your version of pandoc

**Comment by anoronh4** [comment]
Sure! Here's a standalone script with some test data in it:
[generate_biocircos.txt](https://github.com/ramnathv/htmlwidgets/files/10125830/generate_biocircos.txt)
The output of `pandoc -v` is:
```
pandoc 2.19.2
Compiled with pandoc-types 1.22.2.1, texmath 0.12.5.2, skylighting 0.13,
citeproc 0.8.0.1, ipynb 0.2, hslua 2.2.1
Scripting engine: Lua 5.4
User data directory: /home/noronhaa/.local/share/pandoc
Copyright (C) 2006-2022 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

just now i noticed that there's a warning: `[WARNING] Deprecated: --self-contained. use --embed-resources --standalone` when i run the test script, not sure if that's related.

**Comment by kellyasche** [comment]
I wanted to comment here as well and confirm that I've been having the same issue as well. I've exported DT() tables, and charts using ggiraph. Here's a reproducible using DT().

```
library(tidyverse)
library(htmlwidgets)
library(DT)

Name <- c("A", "B")

Value <- c(5438, 3192, 3215, 1660)

df <- data.frame(Name, Value)

table <- datatable(df)

saveWidget(table, file="table.html", selfcontained = TRUE)

```

**Comment by cpsievert** [comment]
It appears this is something that should be fixed in pandoc https://github.com/jgm/pandoc/issues/8475

**Comment by cpsievert** [comment]
We'll provide a fix in htmlwidgets

**Comment by kellyasche** [comment]
Okay thanks!
