### ISSUE TITLE
Pandoc 2.19 has deprecated --self-contained

### ISSUE THREAD

**Issue by dmurdoch** [ramnathv/htmlwidgets#452]
`saveWidget()` calls `pandoc_self_contained_html()` which [calls Pandoc with the `--self-contained` option](https://github.com/ramnathv/htmlwidgets/blob/e375b340140e80ce73db8d0a9dfdb5d3492bc896/R/pandoc.R#L114).  However, Pandoc 2.19 [has deprecated that option](https://pandoc.org/releases.html) in favour of ` --embed-resources --standalone`, and so it gives a warning.  For example, see https://stackoverflow.com/questions/74379298/argument-selfcontained-deprecated-in-htmlwidgetssavewidget .

**Comment by cpsievert** [comment]
This has been addressed via #257
