### ISSUE TITLE
Call "JS function" Incompatibility with other package (reactable)

### ISSUE THREAD

**Issue by jhk0530** [ramnathv/htmlwidgets#477]
Hi, thanks for nice work. 

I use this packag a lot, and really appreciate with it. 

### problem

However (2 days ago) updated version of htmlwidgets crashes with another my favorite package [`reactable`](https://github.com/glin/reactable) (see [issue](https://github.com/glin/reactable/issues/348))

I'm not sure the reason, but **calling custom Javascript function doesn't work**. (`reactable` didn't changed recently)

Below is minimal example code for trying. (the JS function worked in previous version, but not in 1.6.3)

``` r
library(reactable)

reactable(iris[1:5, ], 
    selection = "single", 
    onClick = JS("function(row, column, rowInfo) {
        console.log('asdf');
        row.toggleRowSelected();
      }")
)
```

If you have any idea, please let me know

Thanks.

---

### Note 

I downgraded htmlwidgets package's version into 1.6.2 with below code

``` r
remotes::install_version('htmlwidgets', version = '1.6.2', repos = "http://cran.us.r-project.org")
```

**Comment by msaltieri** [comment]
Same problem here!

**Comment by gadenbuie** [comment]
Thanks for the reports, and apologies for the inconvenience. I will look into this ASAP, but please keep in mind that it's a long holiday weekend in the United States.

In this case, it will be helpful for anyone experiencing this issue to include any additional reproducible examples where `JS()` calls aren't working as expected.

**Comment by jhk0530** [comment]
Hi all, it seems using `reactR` and `htmlwidgets` with dev version 
(install with `remotes::install_github`) works fine with custom JS function

So I think this issue may close when update `htmlwidgets` package for CRAN. 

Thanks.

**Comment by cvaldezerea** [comment]
This problem is not solved

**Comment by gadenbuie** [comment]
> This problem is not solved

Could you clarify? Also note that the fixed version of htmlwidgets hasn't been released to CRAN yet. We're in the process of submitting the release now. If you've tested with the dev version of htmlwidgets and are still encountering issues, please let us know ASAP.

**Comment by jhk0530** [comment]
Now, **1.6.4 version** (which is available with CRAN install) of `htmlwidgets` solve this problem.
@cvaldezerea
