### ISSUE TITLE
Is this OK for input / output widget as well?

### ISSUE THREAD

**Issue by smartinsightsfromdata** [ramnathv/htmlwidgets#52]
I use handsontable.  There are various implementations (including one I've sort of cobbled together from different authors), but it is not implemented properly. As an example proper sizing is not available.

On the other hand it seems that htmlwidgets is mainly designed for output, while one of the advantages of handsontable is that you can also *read* what a user has written into the table.

Should I attempt to port the code I have running into the htmlwidgets scaffolding?

Would it be worth it?

(but then what about things like  <  type: 'output'  > in the js file?)

**Comment by ramnathv** [comment]
I am closing this for now.
