### ISSUE TITLE
findBower() returns NULL

### ISSUE THREAD

**Issue by yutannihilation** [ramnathv/htmlwidgets#53]
I don't install Bower yet, so `scaffoldWidget()` should stop [here](https://github.com/ramnathv/htmlwidgets/blob/08cbb06a3154fa1ca0f210d69f3afe7b6832c0d7/R/scaffold.R#L161):

```R
 if (findBower() == ""){
```

But `findBower()` returns `NULL`, accordingly this if-statement fails.

I think `else` is needed [here](https://github.com/ramnathv/htmlwidgets/blob/08cbb06a3154fa1ca0f210d69f3afe7b6832c0d7/R/scaffold.R#L193), instead of [here](https://github.com/ramnathv/htmlwidgets/blob/08cbb06a3154fa1ca0f210d69f3afe7b6832c0d7/R/scaffold.R#L194) (I'm using Ubuntu 14.04)

**Comment by timelyportfolio** [comment]
@yutannihilation,  can we close this?  Thanks so much for all the widgets.

**Comment by yutannihilation** [comment]
@timelyportfolio, Yes! Now I close this issue. Thanks again for fixing this!
