### ISSUE TITLE
D3.js(not minified) contains corrupted characters after rmarkdown::render()

### ISSUE THREAD

**Issue by yutannihilation** [ramnathv/htmlwidgets#56]
D3.js(not minified) contains corrupted characters after rmarkdown::render()
===
Disclaimer: I don't mean to blame htmlwidgets for this problem, this seems the problem of rmarkdown.

I'm trying to create a widget with [metrics-graphics.js](http://metricsgraphicsjs.org/). The repo is [here](https://github.com/yutannihilation/metricsgraphics). I can successfully render charts in RStudio's view, but I cannot see those charts in knitted Rmarkdown files.

The cause of this seems that D3.js (non-minified version) contains non-ASCII characters and those are converted to corrupted characters.

## Package detail

Before describing the problem, I write about the way I created this package.

I executed the following code; metric-graphics.js, d3.js and jquery are deployed into `inst/htmlwidgets/lib` automatically.

```R
htmlwidgets::scaffoldWidget("metricsgraphics", bowerPkg = "metrics-graphics")
```
I edited R and Javascript a bit.

* [metricsgraphics.R](https://github.com/yutannihilation/metricsgraphics/blob/master/R/metricsgraphics.R)
* [metricsgraphics.js](https://github.com/yutannihilation/metricsgraphics/blob/master/inst/htmlwidgets/metricsgraphics.js#L15-L25)

## Code to draw chart

Here is my code to generate a chart with `metricsgraphics`. I could successfully draw a chart in RStudio's view.

```R
devtools::install_github("yutannihilation/metricsgraphics")

library(metricsgraphics)
library(wikipediatrend)
library(dplyr)

wp_trend() %>%
  transmute(date = as.character(date), value = count) %>%
  metricsgraphics
```
But when I knit the Rmarkdown file that contains the code above, I couldn't see the chart. 

Rmarkdown: https://gist.github.com/yutannihilation/359f3ac06b3cc3cd9a62#file-test-rmd  
knitted HTML: https://gist.github.com/yutannihilation/359f3ac06b3cc3cd9a62#file-test-html

## Problem details

I found this error in my browser's console.

![console_d3js](https://cloud.githubusercontent.com/assets/1978793/5555521/757643f8-8cf6-11e4-94c1-04638a2c49dd.PNG)

The line 1225 has these invalid characters:

![knitted_d3js](https://cloud.githubusercontent.com/assets/1978793/5555525/99988994-8cf6-11e4-9c31-d35bab37269f.PNG)

The same line in RStudio's view (which displays chart correctly) is this:

![rstudio_d3js](https://cloud.githubusercontent.com/assets/1978793/5555540/ff47cb42-8cf6-11e4-9a3e-2fefe2f48be8.png)

I think those widgets that uses minified version of D3.js, such as `networkD3`, won't suffer from this problem. But I'm afraid everyone who tries to create widgets using D3.js by `bowerPkg` option will suffer this problem.

If we can specify Bower options like `--minify`, we may avoid this problem. (c.f. [Install option --minified · Issue #368 · bower/bower](https://github.com/bower/bower/issues/368)) But I'm not sure. Umm...

Do you have some good idea? Sorry for this long post...

(Later, I will report this issue on `rstudio/rmarkdown` also.)

**Comment by yutannihilation** [comment]
Good news: `pandoc` has been fixed the problem by adding `;charset=utf-8` to MIME type (jgm/pandoc#1842). I've confirmed non-minified version of D3.js is knitted correctly with the development version of `pandoc`.

So, with or without minified file, we will be free from this issue in the near future. Should I close this issue? Or do you continue to discuss the way to use `min` file via `bower`? (I'm very curious about this feature! )

**Comment by ramnathv** [comment]
Thanks @yutannihilation . I will leave this issue in for now, since using `min` files is better wherever they are available. It is simple to implement since all we would be doing is replace a `*.js` file with a `*.min.js` file at the same path wherever available.

**Comment by yutannihilation** [comment]
Thanks.

> using `min` files is better wherever they are available.

Agreed! I'm looking forward to see the implementation :)

**Comment by ramnathv** [comment]
@yutannihilation I have pushed a [PR](https://github.com/ramnathv/htmlwidgets/pull/67) that uses minified files in the YAML configuration wherever they are available. If you have some time to test it out, that would be much appreciated.

**Comment by yutannihilation** [comment]
@ramnathv Thanks! I've confirmed the same command `htmlwidgets::scaffoldWidget("metricsgraphics", bowerPkg = "metrics-graphics")` now generates a YAML with minified files.

```yaml
dependencies:
- name: jquery
  version: 2.1.3
  src: htmlwidgets/lib/jquery
  script: dist/jquery.min.js
- name: d3
  version: 3.5.3
  src: htmlwidgets/lib/d3
  script: ./d3.min.js
- name: metrics-graphics
  version: 1.1.0
  src: htmlwidgets/lib/metrics-graphics
  script: dist/metricsgraphics.min.js
  style: dist/metricsgraphics.css
```

Perfect :+1:

**Comment by ramnathv** [comment]
Great! This has been merged into master. I am closing this issue now.
