### ISSUE TITLE
Wish List/ Under Development

### ISSUE THREAD

**Issue by pssguy** [ramnathv/htmlwidgets#66]
The idea of building htmlwidgets seems to be taking off and although the idea is that they are pretty easy to develop, this may be beyond some of us

timelyportfolio  seems to be receiving some suggestions at  [buildingwidgets](https://github.com/timelyportfolio/buildingwidgets) and there have also been several ideas via twitter. I'd be interested in the timeline aspects of [vis.js}(http://visjs.org/)

Is there a way you could set up a catalog of projects perhaps including finished, under development and suggested so that people could get ideas of what could be worked or might be available in the forseeable future

**Comment by timelyportfolio** [comment]
Probably should cross ref #63

**Comment by pssguy** [comment]
Agreed re #63  That gallery would also be pretty inspirational
