### ISSUE TITLE
add `rflot` to the showcase

### ISSUE THREAD

**Issue by timelyportfolio** [ramnathv/htmlwidgets#72]
@jjallaire Through this [line note](https://github.com/ramnathv/htmlwidgets/commit/86a37b5c740f580781b5addac7d0615ffa434dc6#commitcomment-9247025), we were made aware by @gjoneski of [`rflot`](https://github.com/dcenergy/rflot/) already with a gh-pages branch http://dcenergy.github.io/rflot/.  Add to the showcase?

**Comment by jjallaire** [comment]
Let's wait and see what else comes out over the next couple of weeks (I think we only room for 9 or 10 in the showcase and I want a good diversity of visualization types in there)

**Comment by ramnathv** [comment]
I am building a gallery page, that will allow any widget developer to register their widget. This will make widget discovery easier. I agree with @jjallaire that the "showcase" and "gallery" need to be kept separate, since they serve very different purposes.

**Comment by timelyportfolio** [comment]
going to close this since there is limited room in the showcase.  Gallery should pick these up once ready.
