### ISSUE TITLE
issue with RJSONIO

### ISSUE THREAD

**Issue by smartinsightsfromdata** [ramnathv/htmlwidgets#77]
I've just found a problem in the conversion(s) between data.table and RJSONIO.
This is affecting the library I developed: rpivotTable [here](https://github.com/smartinsightsfromdata/rpivotTable) 
I have documented the problem with reproducible code [here](http://stackoverflow.com/questions/28372298/json-issue-bug-with-data-table-and-rjsonio-jsonlite) and reported it to the data.table project.
I think it strengthen the case for htmlwidgets conversion to adopting jsonlite (which does not appear to have the issue).

**Comment by ramnathv** [comment]
As indicated in the answer on SO, this is NOT a bug in `RJSONIO`. It is just a difference in how `jsonlite` and `RJSONIO` treat data frames. We will be switching to `jsonlite` in the long run, as `shiny` adopts `jsonlite`, but until then it will be `RJSONIO`. You can use the `htmlwidgets:::to_json` function to convert your data frame to a list of records and then feed it to `RJSONIO::toJSON` to get the desired output.

**Comment by jjallaire** [comment]
We can't convert to jsonlite until Shiny converts to jsonlite, and Shiny
can't do this until it has all the right knobs to allow it to emulate some
of the behaviors of RJSONIO. We'd certainly all like to do this but it's
not really possible right now so I'd suggest you figure out a local
workaround.

**Comment by timelyportfolio** [comment]
Solution is easy and should be in https://github.com/smartinsightsfromdata/rpivotTable/pull/7 with extensive discussion/debate https://github.com/smartinsightsfromdata/rpivotTable/issues/5.

**Comment by smartinsightsfromdata** [comment]
The issue here is that @timelyportfolio pull is not a "solution" but is a bypass (of course no disrespect intended).  The problem is occurring with iris dataset as iris has a dot in colnames (eliminating the dot eliminates the problem) and is at the edge between data.table, RJSONIO and htmlwidgets. I wonder how the other packages developed with htmlwidgets behave with data.table (or if all have the "forced" conversion to data.frame proposed by @timelyportfolio ).

**Comment by timelyportfolio** [comment]
I don't consider this a workaround until data.table has its own toJSON conversion function.  Until then I think converting to a standard R data structure with data.table's own built-in function is a solution and not a hack.  Nothing is lost since we lose data.table when we go to JavaScript anyways.

**Comment by timelyportfolio** [comment]
As an example just look at how much JJ has had to add to support dates in dygraphs.
