### ISSUE TITLE
sizing policy: viewer.defaultWidth (and Height) ignored?

### ISSUE THREAD

**Issue by kbroman** [ramnathv/htmlwidgets#78]
I'm trying to figure out the best way to make use of `sizingPolicy` for my [R/qtlcharts package](https://github.com/kbroman/qtlcharts/tree/htmlwidgets).

It seems like `viewer.defaultWidth` and viewer.defaultHeight` are ignored in RStudio. That is, the plot expands to fill the viewer frame, no matter what values are provided for these parameters.

I made [a gist with some example code](https://gist.github.com/kbroman/d188b28f337c840d8193) that I was playing with.

**Comment by jjallaire** [comment]
@jcheng5 I confirmed that these options don't seem to be getting through (the widget seems to be just receiving the width and height of the container). Karl has a nice simple repro in the Gist above, could you take a look when you have a chance?

**Comment by timelyportfolio** [comment]
I believe you just need to add `viewer.fill=F`.

```
# sizing policy
sp <- htmlwidgets::sizingPolicy(viewer.defaultWidth=200,
                                viewer.defaultHeight=200,
                                viewer.padding=5,
                                viewer.paneHeight=300,
                                viewer.fill = FALSE
)
```

**Comment by jcheng5** [comment]
Yeah, @timelyportfolio is right. `viewer.fill=TRUE` takes precedence over the size.

**Comment by kbroman** [comment]
Doh. Thanks!

**Comment by timelyportfolio** [comment]
Actually took longer than I care to admit to remember.  Good test :)

**Comment by kbroman** [comment]
@timelyportfolio Never reveal how long things take (whether short or long).
