### ISSUE TITLE
thoughts on htmlwidgets best practices

### ISSUE THREAD

**Issue by timelyportfolio** [ramnathv/htmlwidgets#80]
I wrote this unpolished post today http://www.buildingwidgets.com/blog/2015/2/12/week-06-what-makes-a-good-htmlwidget, and I wonder if any have similar or disparate thoughts.  If so, where might be a good place to express and publicize these.

**Comment by jjallaire** [comment]
I think these are excellent guidelines. Perhaps we should create a Wiki article based on this that we all contribute to and then once we're happy with it promote it to a vignette / article on the htmlwidgets.org site.

**Comment by timelyportfolio** [comment]
Wiki is a great idea.  I started with copy and paste but on iPhone so will clean up later. https://github.com/ramnathv/htmlwidgets/wiki/A-Good-htmlwidget

**Comment by ramnathv** [comment]
I am closing this issue, since the content has already been captured in the wiki.
