### ISSUE TITLE
allow pandoc option setting from saveWidget

### ISSUE THREAD

**Issue by hrbrmstr** [ramnathv/htmlwidgets#81]
When trying to prep some examples for a blog post for a new widget I tripped the following error:

    Stack space overflow: current size 33632 bytes.
    Use `+RTS -Ksize -RTS' to increase it.
    Error: pandoc document conversion failed with error 2

It doesn't happen when knitting, though, so this may just be a weird edge case.

    library(dplyr)
    library(babynames)
    library(streamgraph) # devtools::install_github("hrbrmstr/streamgraph")

    babynames %>%
      filter(grepl("^Kr", name)) %>%
      group_by(year, name) %>%
      tally(wt=n) %>%
      streamgraph("name", "n", "year", offset="zero", interpolate="linear", width=750, height=310) %>%
      sg_legend(show=TRUE, label="Kr- names: ") -> two

    saveWidget(two, "two.html", TRUE)

to reproduce (but a restart of RStudio also cleared the error at least one time for me).

UPDATE

It's pretty reproducible, but even using the extra parameters from the command line (bash, pandoc 1.13.x, os x 10.10.x) didn't solve the issue. I think it requires compiling pandoc to support rts options. ugh. 

folks might just want to be careful when making ginormous vis.

**Comment by simecek** [comment]
Same issue here for Karl Broman iplot (testjs package). Possible solution seems to be setting selfcontained=FALSE

**Comment by ramnathv** [comment]
Thanks for reporting this. We will investigate the issue and figure out potential solutions to fix it.

**Comment by kbroman** [comment]
The problem can be related to the size of the data being placed in the widget. With [R/qtlcharts](http://github.com/kbroman/qtlcharts), I get this stack space overflow error only for the `iplotMScanone` function, and only with larger data sets. Here's an example (a subset of [this gist](https://gist.github.com/kbroman/5d8a4ad051e23b9155b7)):

```r
library(qtl)
library(qtlcharts)
library(htmlwidgets)
data(grav)
grav$pheno <- grav$pheno
grav <- calc.genoprob(grav)
out <- scanone(grav, phe=1:nphe(grav), method="hk")

# this is okay
out_plot1 <- iplotMScanone(out, lodcolumn=1:103)
saveWidget(out_plot1, file="tmp1.html")
 
# this gives "stack space overflow"
out_plot3 <- iplotMScanone(out, lodcolumn=1:104)
saveWidget(out_plot3, file="tmp3.html")
```

**Comment by ramnathv** [comment]
This should be fixed now. See [here](https://github.com/ramnathv/htmlwidgets/commit/299010a3747a9f8df37ee9c3fa041deb4ae50b4f)

**Comment by kbroman** [comment]
Excellent!

**Comment by hrbrmstr** [comment]
agreed! #ty for this!

**Comment by jjallaire** [comment]
BTW I've subsequently discovered that it's best to increase the pandoc
stack size to ~ 512MB for all pandoc operations:

https://github.com/ramnathv/htmlwidgets/commit/259bc3ca06b286c25e20e62a07361d3c18804e5b

So you shouldn't require fiddling with the arguments manually any longer.
