### ISSUE TITLE
htmlwidgets in the wild

### ISSUE THREAD

**Issue by timelyportfolio** [ramnathv/htmlwidgets#98]
https://github.com/BostonGlobe/potholes/search?utf8=%E2%9C%93&q=htmlwidgets

**Comment by abresler** [comment]
Nice sure looks like it!

----------------------
Alex Bresler
abresler@asbcllc.com
​www.asbcllc.com​
917-455-0239​ (cell)​

**Comment by schnee** [comment]
The http://sense.io team is baking htmlwidgets directly into their sample R analysis. Every new Sense user (I think) gets something that looks like:

https://sense.io/schnee/exploring-wikipedia-in-r

(maybe change the title of this "Issue" to "htmlwidgets sightings in the wild"?)

**Comment by timelyportfolio** [comment]
Great to hear.  Thanks so much for providing that link.  Very neat to see.  I changed the title to hopefully gain some other sightings as you suggested.

**Comment by ramnathv** [comment]
This is terrific to hear @schnee . Let us know if there are any features you might want us to add.

**Comment by schnee** [comment]
(to be clear, I'm not part of Sense, but I'll certainly chime in on features for htmlwidgets)

**Comment by ramnathv** [comment]
@schnee Sorry, I should have checked :) Well you are welcome to chime in with feature requests as well :smile:

**Comment by ramnathv** [comment]
I am closing this issue. The links posted here have been moved to a [wiki page](https://github.com/ramnathv/htmlwidgets/wiki/Widgets-in-the-wild)
